<?php
	$page -> addScript("js/jquery-1.8.2.js","js/jquery-ui_1.9.1.js",'js/jquery.form.js','js/mask.js','js/json2.js','js/jquery.countdown.js');
//    $page -> addScript('js/admin.js','views/admin/js/discount.js','views/admin/js/brands.js','views/admin/js/products.js','views/admin/js/reviews.js');
    $page -> addCss("css/reset.css","css/jquery-ui-1.9.1.css","css/admin.css",'css/jquery.countdown.css');
//    $page ->setFavicon('sc_img/favicon2.ico');
$page -> setFavicon('/img/favicon.ico');
$page -> setTitle('StartStroy - Админ. часть');

    if(!$controller -> is('admin','in') and !$controller -> is('admin','login'))
    {
?>
<table id="rez" height="100%" cellpadding="2" cellspacing="0" class="main">
<tr>
<td class='head'>
    <div style="text-align: center;cursor:default;">Вы вошли как  <strong><?=($DLL -> getUser($_SESSION['userID']))?$DLL -> getUser($_SESSION['userID']):'<span style="color:red">unknown</span>';?></strong> | <a href='/admin/in' title='выход'>Выход</a></div>

	<div class='bottom_menu'>
        <a <?=$controller -> is ('admin','products') ? 'style="text-decoration:none"' : 'href="/admin/products"'?>>Товары</a>
        |
        <a <?=$controller -> is ('admin','categories') ? 'style="text-decoration:none"' : 'href="/admin/categories"'?>>Категории</a>
        |
        <a <?=$controller -> is ('admin','firms') ? 'style="text-decoration:none"' : 'href="/admin/firms"'?>>Производители</a>
        |
        <a <?=$controller -> is ('admin','material') ? 'style="text-decoration:none"' : 'href="/admin/material"'?>>Тип материала</a>
        |
        <a <?=$controller -> is ('admin','reviews') ? 'style="text-decoration:none"' : 'href="/admin/reviews"'?>>Отзывы</a>
        |
        <a <?=$controller -> is ('admin','ready_objects') ? 'style="text-decoration:none"' : 'href="/admin/ready_objects"'?>>Готовые обьекты</a>
        |
        <a <?=$controller -> is ('admin','partners') ? 'style="text-decoration:none"' : 'href="/admin/partners"'?>>Партнеры</a>
        |
        <a <?=$controller -> is ('admin','articles') ? 'style="text-decoration:none"' : 'href="/admin/articles"'?>>Статьи</a>
        |
        <a <?=$controller -> is ('admin','banners') ? 'style="text-decoration:none"' : 'href="/admin/banners"'?>>Баннеры</a>
	</div>
</tr>
<?}else{?>
<table id="rez" height="100%" cellpadding="2" cellspacing="0" class="main">
<?}?>
