<?
$root = $_SERVER['DOCUMENT_ROOT'];


$page->addScript('views/admin/js/reviews.js');
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
$db = db::getInstance();
$dm = new db_manager();
?>

<tr>
    <td>

        <div class="title">Отзывы</div>
        <fieldset>
            <a class="underline" style="cursor: pointer" id="add_rw">+ ДОБАВИТЬ ОТЗЫВ</a>
        </fieldset>
        <fieldset>
            <table align="center" style="width:100%;">
                <tr id="form" style="display: none">
                    <td colspan="6">
                        <div id="editor_title" style="font:10pt Verdana;">Добавление нового отзыва</div>
                        <div class="silver">Поля отмеченные <span class="required">*</span> обязательны к заполнению</div>
                        <form method="post" name="add_review">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none" width="100%">
                                <tr>
                                    <td align="right">Имя<span class="required">*</span></td>
                                    <td style="width: 630px"><input style="width:100%" type="text" name="name" value="" /></td>
                                    <td style="vertical-align:middle" rowspan="3"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Отзыв<span class="required">*</span></td>
                                    <td style="width: 630px"><textarea name="text"  rows="8" cols="80"></textarea></td>
                                </tr>
                                <tr>
                                    <td align="right">Отображать</td>
                                    <td style="width: 630px"><input type="checkbox" name="show" /></td>
                                </tr>
                            </table>
                        </form>

                    </td>
                </tr>
                <tr id="form_edit">
                </tr>

                <?
                $sql = "SELECT * FROM reviews ORDER BY id DESC";
                $db->query($sql);
                if($db->getCount()>0)
                {
                    echo '<tr>
                            <td style="width:30px; font-weight: bold;">№</td>
                            <td style="width:150px; font-weight: bold;">Имя</td>
                            <td style="height: 25px; vertical-align:middle; font-weight: bold;">Отзыв</td>
                            <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                            <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                            <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                          </tr>';
                    $arr = $db->getArray();
                    foreach($arr as $val){


                        echo '<tr>';
                        echo '<td>'.$val['id'].'<input type="hidden" name="id" value="'.$val['id'].'" /></td>';
                        echo '<td>'.(($dm->getClientName($val['client_id']))?$dm->getClientName($val['client_id']):'<span style="color:red">не подписан</span>').'</td>';
                        $text = $DLL->substrText($val['text'],300);
                        echo '<td>'.$text['text'].'</td>';
                        if($val['show'] == 1){
                            echo '<td><img src="/img/admin/item_show.png" title="Отображается"/></td>';
                        }
                        else{
                            echo '<td><img src="/img/admin/item_hide.png" title="Скрыт"/></td>';
                        }
                        echo '<td><img src="img/admin/b_edit.png" data-id ="'.$val['id'].'" title="Редактировать" style="cursor: pointer" class="edit"></td>';
                        echo '<td><img src="img/admin/b_drop.png" data-id ="'.$val['id'].'" title="Удалить" style="cursor: pointer" class="del"></td>';
                        echo '</tr>';
                    }
                }
                ?>


            </table>
        </fieldset>
    </td>
</tr>