<?
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/articles.js');
//require_once $root."/lib/class.category.php";
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM ARTICLES WHERE DELETED = 0");
$article = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">Статьи</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ СТАТЬЮ</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="6" style="padding: 10px;">
                        <div style="margin-bottom:10px;font:10pt Verdana;">Добавить новую статью</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none">
                                <tr>
                                    <td align="right">Название</td>
                                    <td style="width: 350px"><input type="text" style="width: 100%"name="article_name"></td>
                                    <td style="vertical-align:middle" rowspan="4"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Короткое описание</td>
                                    <td style="width: 350px"><textarea rows=3  type="text" style="width: 100%"name="article_shortdes"></textarea></td>
                                </tr>

                                <tr>
                                    <td align="right">Текст статьи</td>
                                    <td style="width: 350px">
                                        <button style="width: 32%;" type="button" class="b" title="Жирный"><b>B</b></button>
                                        <button style="width: 32%;" type='button'' class='i' title='Курсив'><i style='font-family: times new roman;'>I</i></button>    <button style="width: 32%;" type="button" class="l" title="Cсылка">URL</button>
                                        <textarea rows=7 style="width: 100%"name="article_text"></textarea>


                                    </td>
                                </tr>

                                <tr>
                                    <td align="right">Изображение</td>
                                    <td style="width: 350px"><input type="file" style="width: 100%"name="article_img">
                                        <input type="hidden" name="article_img_val">
                                        <img id="id_img_edit_img" style="display:none"/>
                                    </td>

                                </tr>
                                <tr>
                                    <td align="right">Превью</td>
                                    <td style="width: 350px"><input type="file" style="width: 100%"name="article_thumb">
                                                       <input type="hidden" name="article_thumb_val">
                                        <img id="id_img_edit" style="display:none"/>
                                    </td>

                                </tr>

                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($article)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Короткое описание</td>

                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Превью</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Редактировать</td>
                        <td style="width:70px; height: 25px; vertical-align:middle; font-weight: bold;">Удалить</td>
                    </tr>
                    <?foreach($article as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>
                        <td><?echo $cat['shortDes'];?></td>

                        <td><img src="/img/articles/<?echo $cat['thumb'];?>"/></td>
                       <td><button type="button" class="edit" data-id="<?echo $cat['id'];?>">Редактировать</button></td>
                        <td><button type="button" class="del" data-id="<?echo $cat['id'];?>">Удалить</button></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент статей нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>