<?
    $root = $_SERVER['DOCUMENT_ROOT'];
    require_once $root."/lib/class.invis.db.php";
    require_once $root."/lib/class.db.manager.php";
    $action = $controller -> getParam(1);
    $id = (int)$controller -> getParam(2);
    $db = db::getInstance();
    $dm = new db_manager();
?>
 
<tr style="height:50px;">
    <td>
    <div class="back"><a href="/admin/products">НАЗАД</a></div>
        <div class="title"><?=($action == 'add')?'Добавление':'Редактирование';?> товаров</div>
    </td>
</tr>
<tr>
    <td>


        <form>
        <input type="hidden" name="action" value="<?=$action?>" />
        <input type="hidden" name="id" value="<?=$id?>" />
        <?
        if($action == 'add')
        {
        ?>
        <table style="width:100%">
            <tr >
                <td style="width:30%">Отображать на сайте<p class="silver">Отметьте, чтобы товар отображался на сайте</p></td>
                <td style="width:70%"><input type="checkbox" name="show" /></td>
            </tr>
            <tr class="for_present">
                <td>Это подарок<p class="silver">Отметьте, если данный товар является подарком</p></td>
                <td><input type="checkbox" name="is_present"/></td>
            </tr>
            <tr class="for_present">
                <td>Название*<p class="silver">Обязательное поле</p></td>
                <td><input type="text" name="name" value="" style="width:350px" /></td>
            </tr>
            <tr class="for_present">
                <td>Артикул</td>
                <td><input type="text" name="article" value="" /></td>
            </tr>
            <tr>
                <td>Тип</td>
                <td>
                    <select name="type">
                        <option value="жен">Женские</option>
                        <option value="муж">Мужские</option>
                        <option value="дет">Детские</option>
                        <option value="уни">Унисекс</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Бренд</td>
                <td>
                    <select name="brand">
                        <?
                        $sql = "SELECT id,name FROM brands";
                        $db->query($sql);
                        if($db->getCount()>0)
                        {
                            $arr = $db->getArray();
                            echo '<option value="0">Выберите бренд</option>';
                            foreach($arr as $key =>$val){
                                echo '<option value="'.$val['id'].'">'.$val['name'].'</option>';
                            }
                        }
                        ?>
                    </select>
                </td>
            </tr>

            <tr>
                <td>Приоритет<p class="silver">Выберите приоритет отображения товара. Чем выше приоритет, тем выше в списке товаров данный продукт выводится</p></td>
                <td>
                    <select name="priority">
                        <?
                        for($i = 1;$i<=10;$i++){
                            echo '<option value="'.$i.'">'.$i.'</option>';
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Цена<p class="silver">Введите цену товара в грн.</p></td>
                <td><input type="text" name="price" value="" /> грн.</td>
            </tr>
            <tr>
                <td>Постоянная скидка<p class="silver">Независимая скидка на товар (число от 0 до 100)</p></td>
                <td><input type="text" name="const_discount" value="" /> %</td>
            </tr>
            <tr>
                <td>Дополнительные скидки<p class="silver">Установка дополнительных скидок к товару. Скидка добавляется после нажатия кнопки "Добавить".</p></td>
                <td>
                    <select name="discounts">
                        <option value="0">Выберите тип скидки</option>
                        <option value="timer">Скидка с таймером</option>
                        <option value="count">Скидка по количеству товара</option>
                    </select>
                    <input type="button" value="Добавить" id="add_discount"/>
                    <fieldset id="timer_discount" class="display_none">
                        <div class="del_discount" title="Удалить скидку"><img src="sc_img/admin/remove.png" /></div>
                        <div style=" font-size: 20px; margin-bottom: 19px; font-weight: bold;">Скидка с таймером</div>
                        <div style="margin-bottom: 3px;font-weight: bold;">Время запуска таймера</div>
                        <div>
                            <input type="text" name="date_start" value="<?=date('d.m.Y')?>" />
                            <select name="start_hours">
                                <?
                                for($i = 0; $i<=23; $i++){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                            </select>
                            часов
                            <select name="minutes_start">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                            </select>
                            минут
                        </div>
                        <div style=" margin-top: 18px;margin-bottom: 3px;font-weight: bold;">Длительность первого периода работы таймера</div>
                        <div>
                            <select name="days_d">
                                <?
                                for($i = 0; $i<100; $i++){
                                    echo '<option value="'.$i.'">'.$i.'</option>';                                }
                                ?>
                            </select>
                            дней
                            <select name="hours_d">
                                <?
                                for($i = 0; $i<=23; $i++){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                                ?>
                            </select>
                            часов
                            <select name="minutes_d">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                            </select>
                            минут&nbsp;
                            Скидка <input type="text" name="percent_d1" value=""/> %
                        </div>

                        <div style=" margin-top: 20px; margin-bottom: 3px;font-weight: bold;">Длительность второго периода работы таймера</div>
                        <div>
                            <select name="days_d2">
                                <?
                                for($i = 0; $i<100; $i++){
                                    echo '<option value="'.$i.'">'.$i.'</option>';                                }
                                ?>
                            </select>
                            дней
                            <select name="hours_d2">
                                <?
                                for($i = 0; $i<=23; $i++){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                            </select>
                            часов
                            <select name="minutes_d2">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                }
                                ?>
                            </select>
                            минут&nbsp;
                            Скидка <input type="text" name="percent_d2" value=""/> %
                        </div>
                        <div style=" margin-top: 20px; font-weight: bold; color: rgb(114, 19, 19);">Закольцевать таймер
                            <input type="checkbox" name="ring_timer" title="В данном случае по истечении второго таймера запустится первый"/>
                        </div>
                        <div style=" margin-top: 20px; font-weight: bold; color: rgb(114, 19, 19);">Временно приостановить действие скидки
                        <input type="checkbox" name="on_timer" title="В данном случае скидка будет отключена, но вы сможете восстановить ее действие"/>
                        </div>
                    </fieldset>
                    <fieldset id="count_discount" class="display_none">
                        <div class="del_discount" title="Удалить скидку"><img src="sc_img/admin/remove.png" /></div>
                        <div style=" font-size: 20px; margin-bottom: 19px; font-weight: bold;">Скидка по количеству товара</div>
                        <div style="margin-bottom: 3px;font-weight: bold;">Количество товара</div>
                        <div><input type="text" name="count_prod" value="" /> шт.</div>
                        <div style="margin-top: 15px;margin-bottom: 3px;font-weight: bold;">Размер скидки</div>
                        <div><input type="text" name="percent_cd" value="" /> %</div>
                        <div style=" margin-top: 15px; font-weight: bold; color: rgb(114, 19, 19);">Временно приостановить действие скидки
                            <input type="checkbox" name="on_count" title="В данном случае скидка будет отключена, но вы сможете восстановить ее действие"/>
                        </div>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    Подарок<p class="silver">После нажатия кнопки "Добавить", к товару добавляется подарок из списка. Данные сохраняются после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                    <div>
                        <select name="presents">
                            <option value="0">Выберите подарок</option>
                            <?
                            $sql = "SELECT id, name FROM products WHERE is_present = 1";
                            $db->query($sql);
                            if($db->getCount()>0){
                                $arr = $db->getArray();
                                foreach($arr AS $key =>$val){
                                    echo '<option value="'.$val['id'].'">'.$val['name'].'</option>';
                                }
                            }
                            ?>
                        </select>
                        <input type="button" id="add_present" value="Добавить"/>
                    </div>
                    <div id="for_present">

                    </div>
                </td>
            </tr>
            <tr class="for_present">
                <td>
                    Фотография<p class="silver">Главная фотография товара. Размер картинки должен быть не меньше чем 450px*426px. Формат *.jpg. Изображение сохраняется после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                   <div><input type="file" name="main_img" /><span id="preloader"></span></div>
                   <div id="for_image">                   </div>
                </td>
            </tr>
        <tr>
            <td>
                Видеоролик<p class="silver">Вставьте ссылку на видеоролик с сайта youtube.com и нажмите кнопку "Добавить". Данные сохраняются после нажатия кнопки "Сохранить"</p>
            </td>
            <td>
                <div>Ссылка на видеоролик YouTube <input type="text" name="video_link" /> <input type="button" name="add_video" value="Добавить" /><span id="preloader_v"></span></div>
                <div id="for_video">
                    <input type="hidden" name="video" value="">
                </div>
            </td>
        </tr>
        <tr>
            <td>
               Фотогалерея<p class="silver">Фотоконтент товара, который отображается в слайдере. Высота фотографий не должна быть меньшей 426px. Данные сохраняются после нажатия кнопки "Сохранить"</p>
            </td>
            <td>
                <div><input type="file" name="photo_gallery[]" multiple="multiple" /><input type="button" id="load_imgs" value="Загрузить" /><span id="preloader_g"></span></div>
                <div id="for_gallery"></div>
                <div class='clear'></div>
                <div id="for_mistakes"></div>
            </td>
        </tr>
        <tr>
            <td>
                Характеристики<p class="silver">Кнопкой "Добавить характеристику" можно добавить неограниченное количество характеристик. Незаполненные поля в базу не сохраняются</p>
            </td>
            <td>
                <input type="hidden" name="char_count" value="0" />
                <input type="button" id="add_char" value="Добавить характеристику" />
            </td>
        </tr>
        <tr class="for_present">
            <td>
                Описание<p class="silver">Полное описание товара</p>
            </td>
            <td>
               <textarea name="description" rows="8" cols="80"></textarea>
            </td>
        </tr>
        </table>
        <?
        }

        if($action == 'edit' && $id > 0)
        {
            $c = $dm->getProductById($id);
            $show = ($c->get_show() == 1)?'checked':'';
            $is_present = ($c->get_is_present() == 1)?'checked':'';
            $hide = ($c->get_is_present() == 1)?'style="display:none"':'';
        ?>
            <table>
            <tr <?=$hide?>>
                <td>Отображать на сайте<p class="silver">Отметьте, чтобы товар отображался на сайте</p></td>
                <td><input type="checkbox" name="show" <?=$show?>/></td>
            </tr>
            <tr class="for_present">
                <td>Это подарок<p class="silver">Отметьте, если данный товар является подарком</p></td>
                <td><input type="checkbox" name="is_present" <?=$is_present?>/></td>
            </tr>
            <tr class="for_present">
                <td>Название*<p class="silver">Обязательное поле</p></td>
                <td><input type="text" name="name" style="width:350px" value="<?=$c->get_name()?>" /></td>
            </tr>
            <tr class="for_present">
                <td>Артикул</td>
                <td><input type="text" name="article" value="<?=$c->get_article()?>" /></td>
            </tr>
            <tr <?=$hide?>>
                <td>Тип</td>
                <td>
                    <select name="type">
                        <option value="жен" <?echo ($c->get_type() == 'жен')?' selected':'';?>>Женские</option>
                        <option value="муж" <?echo ($c->get_type() == 'муж')?' selected':'';?>>Мужские</option>
                        <option value="дет" <?echo ($c->get_type() == 'дет')?' selected':'';?>>Детские</option>
                        <option value="уни" <?echo ($c->get_type() == 'уни')?' selected':'';?>>Унисекс</option>
                    </select>
                </td>
            </tr>

            <tr <?=$hide?>>
                <td>Бренд</td>
                <td>
                    <select name="brand">
                        <?
                        $sql = "SELECT id,name FROM brands";
                        $db->query($sql);
                        if($db->getCount()>0)
                        {
                            $arr = $db->getArray();
                            echo '<option value="0">Выберите бренд</option>';
                            foreach($arr as $key =>$val){
                                $selected = ($val['id'] == $c->get_brand_id())?"selected":"";
                                echo '<option value="'.$val['id'].'" '.$selected.'>'.$val['name'].'</option>';
                            }
                        }
                        ?>
                    </select>
                </td>
            </tr>

            <tr <?=$hide?>>
                <td>Приоритет<p class="silver">Выберите приоритет отображения товара. Чем выше приоритет, тем выше в списке товаров данный продукт выводится</p></td>
                <td>
                    <select name="priority">
                        <?
                        for($i = 1;$i<=10;$i++){
                            $selected = ($i == $c->get_priority())?"selected":"";
                            echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                        }
                        ?>
                    </select>
                </td>
            </tr>

            <tr <?=$hide?>>
                <td>Цена<p class="silver">Введите цену товара в грн.</p></td>
                <td><input type="text" name="price" value="<?=$c->get_price()?>" /> грн.</td>
            </tr>
            <tr <?=$hide?>>
                <td>Постоянная скидка<p class="silver">Независимая скидка на товар (число от 0 до 100)</p></td>
                <td><input type="text" name="const_discount" value="<?=$c->get_discount()?>" /> %</td>
            </tr>
            <tr <?=$hide?>>
                <td>Дополнительные скидки<p class="silver">Установка дополнительных скидок к товару. Скидка добавляется после нажатия кнопки "Добавить".</p></td>
                <td>
                    <select name="discounts">
                        <option value="0">Выберите тип скидки</option>
                        <option value="timer">Скидка с таймером</option>
                        <option value="count">Скидка по количеству товара</option>
                    </select>
                    <input type="button" value="Добавить" id="add_discount"/>
                    <fieldset id="timer_discount" <?echo ($dm->hasTimer($c->get_id()))?'':'class="display_none"';?>>

                       <?
                       if($dm->hasTimer($c->get_id()))
                       {
                           echo '<input type="hidden" name="with_timer_discount" value="1">';
                           $t = $dm->getFullInfoAboutTimerByProductId($c->get_id());
                           $d1 = $t->get_timer()->getDurationInStrFormat();
                           $d2 = $t->get_timer2()->getDurationInStrFormat();
                           $s  = $t->get_smart_date();
                       }
                       ?>
                        <div class="del_discount" title="Удалить скидку"><img src="sc_img/admin/remove.png" /></div>
                        <div style=" font-size: 20px; margin-bottom: 19px; font-weight: bold;">Скидка с таймером</div>
                        <div style="margin-bottom: 3px;font-weight: bold;">Время запуска таймера</div>
                        <div>
                            <input type="text" name="date_start" value="<?=($dm->hasTimer($c->get_id()))?$s['date']:date('d.m.Y')?>" />
                            <select name="start_hours">
                                <?
                                for($i = 0; $i<=23; $i++){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    if($dm->hasTimer($c->get_id()))
                                    {
                                    $selected = ($i == $s['hours'])?" selected":'';
                                    echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                    }
                                    else
                                    {
                                        echo '<option value="'.$i.'">'.$i.'</option>';
                                    }
                                }
                                ?>
                            </select>
                            часов
                            <select name="minutes_start">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    if($dm->hasTimer($c->get_id()))
                                    {
                                        $selected = ($i == $s['minutes'])?"selected":'';
                                        echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                    }
                                    else
                                    {
                                        echo '<option value="'.$i.'">'.$i.'</option>';
                                    }
                                }
                                ?>
                            </select>
                            минут
                        </div>
                        <div style=" margin-top: 18px;margin-bottom: 3px;font-weight: bold;">Длительность первого периода работы таймера</div>
                        <div>
                            <select name="days_d">
                                <?
                                for($i = 0; $i<100; $i++){
                                    if($dm->hasTimer($c->get_id()))
                                    {
                                        $selected = ($i == $d1['days'])?" selected":'';
                                        echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                    }
                                    else
                                    {
                                        echo '<option value="'.$i.'" >'.$i.'</option>';
                                    }
                                }
                                ?>
                            </select>
                            дней
                            <select name="hours_d">
                                <?
                                for($i = 0; $i<=23; $i++){
                                    if($dm->hasTimer($c->get_id()))
                                    {
                                    $selected = ($i == $d1['hours'])?" selected":'';
                                    }
                                    else
                                    {
                                        $selected ='';
                                    }
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                }
                                ?>
                                ?>
                            </select>
                            часов
                            <select name="minutes_d">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                    if($dm->hasTimer($c->get_id()))
                                    {
                                        $selected = ($i == $d1['minutes'])?" selected":'';
                                    }
                                    else
                                    {
                                        $selected ='';
                                    }
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                }
                                ?>
                            </select>
                            минут&nbsp;
                            Скидка <input type="text" name="percent_d1" value="<?=($dm->hasTimer($c->get_id()))?$t->get_percentDiscount():''?>"/> %
                        </div>
<?
if($dm->hasTimer($c->get_id()))
{
    $t = $dm->getFullInfoAboutTimerByProductId($c->get_id());
    if(!$t->get_timer()->isTimeout() && $t->get_on() == 1)
    {
        echo '<div class="for_countdown" data-until="'.$t->get_timer()->GetTimeLeft().'" ></div>';
    }
}
?>
                        <div style=" margin-top: 20px; margin-bottom: 3px;font-weight: bold;">Длительность второго периода работы таймера</div>
                        <div>
                            <select name="days_d2">
                                <?
                                for($i = 0; $i<100; $i++){
                                if($dm->hasTimer($c->get_id()))
                                {
                                    $selected = ($i == $d2['days'])?" selected":'';
                                }
                                else{
                                    $selected ='';
                                }
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';                                }
                                ?>
                            </select>
                            дней
                            <select name="hours_d2">
                                <?
                                for($i = 0; $i<=23; $i++){
                                if($dm->hasTimer($c->get_id()))
                                {
                                    $selected = ($i == $d2['hours'])?" selected":'';
                                }else{
                                    $selected = '';
                                }
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                }
                                ?>
                            </select>
                            часов
                            <select name="minutes_d2">
                                <?
                                for($i = 0; $i<60; $i +=15){
                                if($dm->hasTimer($c->get_id()))
                                {
                                    $selected = ($i == $d2['minutes'])?" selected":'';
                                }else{
                                    $selected = '';
                                }
                                    if($i<10){
                                        $i = '0'.$i;
                                    }
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                }
                                ?>
                            </select>
                            минут&nbsp;
                            Скидка <input type="text" name="percent_d2" value="<?=($dm->hasTimer($c->get_id()))?$t->get_percentDiscount2():''?>"/> %
                        </div>
                <?
                if($dm->hasTimer($c->get_id()))
                {
                    $t = $dm->getFullInfoAboutTimerByProductId($c->get_id());
                    if(!$t->get_timer2()->isTimeout() && $t->get_on() == 1)
                    {
                        echo '<div class="for_countdown" data-until="'.$t->get_timer2()->GetTimeLeft().'" ></div>';
                    }
                }
                ?>
                        <div style=" margin-top: 20px; font-weight: bold; color: rgb(114, 19, 19);">Закольцевать таймер
                            <?
                            if($dm->hasTimer($c->get_id())){
                                $checked = ($t->get_ringed() == 1)?'checked':'';
                            }
                            else{
                                $checked = '';
                            }
                            ?>

                            <input type="checkbox" <?=$checked?> name="ring_timer" title="В данном случае по истечении второго таймера запустится первый"/>
                        </div>
                        <div style=" margin-top: 15px; font-weight: bold; color: rgb(114, 19, 19);">Временно приостановить действие скидки
                            <input type="checkbox" name="on_timer" <?
                            if($dm->hasTimer($c->get_id())){
                                echo ($t->get_on() == 1)?'':'checked';
                            }
                            else{
                                echo '';
                            }
                            ?> title="В данном случае скидка будет отключена, но вы сможете восстановить ее действие"/>
                        </div>
                    </fieldset>
                    <?
                        if($dm->hasCount($c->get_id())){
                            $cd = $dm->getFullInfoAboutCountByProductId($c->get_id());
                            if($cd->get_on() == 1){
                                $ch = '';
                            }else{
                                $ch = " checked";
                            }
                        }
                        else{
                            $ch = '';
                        }
                    ?>

                    <fieldset id="count_discount" <?echo ($dm->hasCount($c->get_id()))?'':'class="display_none"';?>>
                        <?
                        if($dm->hasCount($c->get_id()))
                        {
                            echo '<input type="hidden" name="with_count_discount" value="1">';
                        }
                        ?>
                        <div class="del_discount" title="Удалить скидку"><img src="sc_img/admin/remove.png" /></div>
                        <div style=" font-size: 20px; margin-bottom: 19px; font-weight: bold;">Скидка по количеству товара</div>
                        <div style="margin-bottom: 3px;font-weight: bold;">Количество товара</div>
                        <div><input type="text" name="count_prod" value="<?=($dm->hasCount($c->get_id()))?$cd->get_available():''?>" /> шт.</div>
                        <?=($dm->hasCount($c->get_id()))?'Продано: '.$cd->get_sold().'шт.':''?>
                        <div style="margin-top: 15px;margin-bottom: 3px;font-weight: bold;">Размер скидки</div>
                        <div><input type="text" name="percent_cd" value="<?=($dm->hasCount($c->get_id()))?$cd->get_percent():''?>" /> %</div>
                        <div style=" margin-top: 15px; font-weight: bold; color: rgb(114, 19, 19);">Временно приостановить действие скидки
                            <input type="checkbox" name="on_count" <?=$ch?> title="В данном случае скидка будет отключена, но вы сможете восстановить ее действие"/>
                        </div>
                    </fieldset>
                </td>
            </tr>
            <tr <?=$hide?>>
                <td>
                    Подарок<p class="silver">После нажатия кнопки "Добавить", к товару добавляется подарок из списка. Данные сохраняются после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                    <div>
                        <select name="presents">
                            <option value="0">Выберите подарок</option>
                            <?
                            $sql = "SELECT id, name FROM products WHERE is_present = 1";
                            $db->query($sql);
                            if($db->getCount()>0){
                                $arr = $db->getArray();
                                foreach($arr AS $key =>$val){
                                    echo '<option value="'.$val['id'].'">'.$val['name'].'</option>';
                                }
                            }
                            ?>
                        </select>
                        <input type="button" id="add_present" value="Добавить"/>
                    </div>
                    <div id="for_present">
                        <?
                            if($dm->hasPresent($c->get_id())){

                                $pr = $dm->getAllInfoAboutPresentByProductId($c->get_id());
                                $checked = ($pr->get_on() == 1)?'':' checked';



                                echo '<div class="del_present" title="Удалить подарок"><img src="sc_img/admin/remove.png" /></div>';
                                echo '<div style="margin: 20px 0;"><img src="sc_img/surprize.png"> Подарок: '.$dm->getProductNameById($pr->get_present_id()).'</div>';
                                echo '<input type="hidden" name="with_present" value="1" />';
                                echo '<input type="hidden" name="present_id" value="'.$pr->get_present_id().'" />';
                                echo '<div style="margin-bottom: 3px;font-weight: bold;">Количество подарков</div>';
                                echo '<div><input type="text" name="present_count" value="'.$pr->get_available().'"/> шт.</div>';
                                echo 'Продано: '.$pr->get_sold()."шт.";

                                echo '<div style="margin-top: 20px;font-weight: bold;color: rgb(114, 19, 19);">Временно приостановить выдачу подарков
                                      <input type="checkbox" name="on_present" '.$checked.' title="В данном случае скидка будет отключена, но вы сможете восстановить ее действие"/>
                                      </div>';
                            }
                        ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    Фотография<p class="silver">Главная фотография товара. Размер картинки должен быть не меньше чем 450px*426px. Формат *.jpg. Изображение сохраняется после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                    <div><input type="file" name="main_img" /><span id="preloader"></span></div>
                    <div  id="for_image">
                        <img style="margin:25px;height: 107px" src="sc_img/product/<?=$c->get_photo()?>.jpg" />
                        <input type="hidden" name="photo" value="<?=$c->get_photo()?>">
                    </div>
                </td>
            </tr>
            <tr <?=$hide?>>
                <td>
                    Видеоролик<p class="silver">Вставьте ссылку на видеоролик с сайта youtube.com и нажмите кнопку "Добавить". Данные сохраняются после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                    <div>Ссылка на видеоролик YouTube <input style="width:350px" type="text" name="video_link" /> <input type="button" name="add_video" value="Добавить" /><span id="preloader_v"></span></div>
                    <div id="for_video">
                        <?
                        if($c->get_video() != ''){
                            echo '<div class="del_video" title="Удалить скидку"><img src="sc_img/admin/remove.png" /></div>
                                    <object width="400" height="240">
                                    <param name="movie" value="'.$c->get_video().'"></param>
                                    <param name="allowFullScreen" value="true"></param>
                                    <param name="allowscriptaccess" value="always"></param>
                                    <embed src="'.$c->get_video().'" type="application/x-shockwave-flash" width="400" height="240" allowscriptaccess="always" allowfullscreen="true"></embed>
                                    </object>
                                    <div><input type="hidden" name="video" value="'.$c->get_video().'"></div>';
                        }
                        ?>
                    </div>
                </td>
            </tr>
            <tr <?=$hide?>>
                <td>
                    Фотогалерея<p class="silver">Фотоконтент товара, который отображается в слайдере. Высота фотографий не должна быть меньшей 426px. Данные сохраняются после нажатия кнопки "Сохранить"</p>
                </td>
                <td>
                    <div><input type="file" name="photo_gallery[]" multiple="multiple" /><input type="button" id="load_imgs" value="Загрузить" /><span id="preloader_g"></span></div>
                    <div id="for_gallery">
                    <?
                    $gallery = $dm->getPhotoGal($c->get_id());
                    foreach($gallery AS $i => $val)
                    {
                        echo '<div class="float_left"><img src="../sc_img/product/'.$val['photo'].'" height="60" class="sm_img"/><img class="del_gal_photo" src="../sc_img/admin/b_drop.png" /></div>';
                    }
                    ?>
                    </div>
                </td>
            </tr>
            <tr <?=$hide?>>
                <td>
                    Характеристики<p class="silver">Кнопкой "Добавить характеристику" можно добавить неограниченное количество характеристик. Незаполненные поля в базу не сохраняются</p>
                </td>
                <td>
                    <?
                    $items = $dm->getProductItems($id);
                    foreach($items AS $index => $item)
                    {
                        echo '<div class="char">';
                        echo 'Наименование: ';
                        echo '<input style="width: 150px;margin-right: 29px;" name="c_name_'.($index+1).'" type="text"  class="name" value="'.$item['title'].'"/>';
                        echo ' Значение: ';
                        echo '<input style="width: 252px;" name="c_value_'.($index+1).'" type="text" class="value" value="'.$item['text'].'"/>';
                        echo '<div class="del_char" title="Удалить характеристику"><img src="sc_img/admin/remove.png" /></div>';
                        echo '</div>';
                    }
                    ?>
                    <input type="hidden" name="char_count" value="<?=count($items)?>" />
                    <input type="button" style="margin: 20px 0;" id="add_char" value="Добавить характеристику" />
                </td>
            </tr>
            <tr class="for_present">
                <td>
                    Описание<p class="silver">Полное описание товара</p>
                </td>
                <td>
                    <textarea name="description" rows="8" cols="80"><?=$c->get_description()?></textarea>
                </td>
            </tr>
            </table>
        <?
        }
        ?>
        <input type="button" id="save_product" class="btnSave" value="Сохранить">
        </form>
    </td>
</tr>




