<?
$root = $_SERVER['DOCUMENT_ROOT'];
require_once $root."/lib/class.invis.db.php";
$db = db :: getInstance();
?>
<tr>
    <td>
        <div class="title">Бренды</div>
        <fieldset>
            <table align="center" style="width:100%;">
                <tr>
                    <td style="width:30px;">№</td>
                    <td style="width:850px; height: 25px; vertical-align:middle; font-weight: bold;">Наименование</td>
                    <td style=" height: 25px; vertical-align:middle; font-weight: bold;">Обновить</td>
                    <td style=" height: 25px; vertical-align:middle; font-weight: bold;">Удалить</td>
                </tr>
                <?
                    $sql = "SELECT * FROM brands";
                    $db->query($sql);
                if($db->getCount()>0)
                {
                    $arr = $db->getArray();
                    foreach($arr as $key =>$val){
                        echo '<tr>';
                        echo '<td>';
                        echo $key+1;
                        echo '</td>';
                        echo '<td class="brand_info">';
                        echo '<input type = "text" name = "brand" value="'.$val['name'].'" style="width:500px"/>';
                        echo '<input type = "hidden" name = "brand_id" value="'.$val['id'].'" />';
                        echo '</td>';
                        echo '<td>';
                        echo '<input type = "button" class="refresh" value="Обновить"';
                        echo '</td>';
                        echo '<td>';
                        echo '<img class="del_brand" src="sc_img/admin/b_drop.png" title="Удалить">';
                        echo '</td>';
                    }
                }
                ?>
                <tr id="form">
                    <td colspan="4">
                        <span>Добавить новый бренд</span>
                        <form method="post">
                        <input type="text" name="new_brand" value="" style="width:600px;height: 18px;"/>
                            <input type="submit" value="Добавить" id="add_brand"/>
                        </form>
                    </td>
                </tr>
            </table>
        </fieldset>
    </td>
</tr>