<?
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/firms.js');
//require_once $root."/lib/class.category.php";
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM firms WHERE deleted = 0 ORDER BY id DESC");
$firms = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">ФИРМЫ</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ ПРОИЗВОДИТЕЛЯ</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="6" style="padding: 10px;">
                        <div id="editor_title" style="font:10pt Verdana;">Добавление нового производителя</div>
                        <div class="silver">Поля отмеченные <span class="required">*</span> обязательны к заполнению</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none" width="100%">
                                <tr>
                                    <td align="right">Название<span class="required">*</span></td>
                                    <td style="width: 630px"><input type="text" style="width: 100%"name="firm_name"></td>
                                    <td style="vertical-align:middle"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($firms)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                        <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                        <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                    </tr>
                    <?foreach($firms as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>
                        <td><img src="img/admin/b_edit.png" data-id ="<?=$cat['id']?>" data-name="<?echo $cat['name']?>" title="Редактировать" style="cursor: pointer" class="edit"></td>
                        <td><img src="img/admin/b_drop.png" data-id ="<?=$cat['id']?>" title="Удалить" style="cursor: pointer" class="del"></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент фирм нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>