<?

require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/products.js');
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM products WHERE DELETED = 0");
$product = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">Товары</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ ТОВАР</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="11" style="padding: 10px;">
                        <div style="margin-bottom:10px;font:10pt Verdana;">Добавить новый товар</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none">
                                <tr>
                                    <td align="right">Название</td>
                                    <td style="width: 670px"><input type="text" style="width: 100%"name="product_name"></td>
                                    <td style="vertical-align:middle" rowspan="4"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Описание</td>
                                    <td style="width: 350px"><textarea rows=3  type="text" style="width: 100%"name="product_des"></textarea></td>
                                </tr>

                                <tr>
                                    <td align="right">Цена</td>
                                    <td style="width: 350px"><input type="text" style="width: 100%"name="product_price"></td>
                                </tr>
                                <tr>
                                    <td align="right">Новая цена</td>
                                    <td style="width: 350px"><input type="text" style="width: 100%"name="product_priceforsale"></td>
                                </tr>
                                <tr>
                                    <td align="right">Изображение</td>
                                    <td style="width: 350px"><input type="file" style="width: 100%"name="product_img">
                                        <input type="hidden" name="product_img_val">
                                        <img id="id_img_edit_img" style="display:none"/>
                                    </td>

                                </tr>
                                <tr>
                                    <td align="right">Категория</td>
                                    <td>
                                        <?echo $dm->getCategorySelect('category_id')?>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">Выбирете производителя</td>
                                    <td>
                                        <?echo $dm->getFirmSelect('firm')?>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">Тип материала</td>
                                    <td>
                                        <?echo $dm->getMaterialSelect('material')?>
                                    </td>
                                </tr>

                                <tr>
                                    <td align="right">Характеристики</td>
                                    <td>
                                        <input type="hidden" name="char_count" value="0">
                                        <input type="button" id="add_char" value="Добавить характеристику">
                                    </td>
                                </tr>



                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($product)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Название</td>

                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Цена</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Новая цена</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Категория</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Производитель</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Тип материала</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Изображение</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Редактировать</td>
                        <td style="width:70px; height: 25px; vertical-align:middle; font-weight: bold;">Удалить</td>
                    </tr>
                    <?foreach($product as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>

                        <td><?echo $cat['price'];?></td>
                        <td><?echo $cat['priceForSale'];?></td>
                        <td><?echo $dm-> getCategoryName( $cat['category_id']);?></td>
                        <td><?echo $dm-> getFirmName( $cat['firm_id']);?></td>
                        <td><?echo $dm-> getMaterialName( $cat['material_id']);?></td>
                        <td><img src="/img/products/m_<?echo $cat['img'];?>"/></td>
                        <td><button type="button" class="edit" data-id="<?echo $cat['id'];?>">Редактировать</button></td>
                        <td><button type="button" class="del" data-id="<?echo $cat['id'];?>">Удалить</button></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент товаров нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>