<?
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/firms.js');
//require_once $root."/lib/class.category.php";
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM FIRMS WHERE DELETED = 0");
$firms = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">ФИРМЫ</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ ФИРМУ</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="6" style="padding: 10px;">
                        <div style="margin-bottom:10px;font:10pt Verdana;">Добавить новую фирму</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none">
                                <tr>
                                    <td align="right">Название</td>
                                    <td style="width: 350px"><input type="text" style="width: 100%"name="firm_name"></td>
                                    <td style="vertical-align:middle" rowspan="2"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($firms)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                        <td style="width:90px; height: 25px; vertical-align:middle; font-weight: bold;">Редактировать</td>
                        <td style="width:70px; height: 25px; vertical-align:middle; font-weight: bold;">Удалить</td>
                    </tr>
                    <?foreach($firms as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>
                        <td><button type="button" class="edit" data-id="<?echo $cat['id'];?>" data-name="<?echo $cat['name']?>" >Редактировать</button></td>
                        <td><button type="button" class="del" data-id="<?echo $cat['id'];?>">Удалить</button></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент фирм нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>