<?
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/partners.js');
//require_once $root."/lib/class.category.php";
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM partners WHERE deleted = 0 ORDER BY id DESC");
$partner = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">ПАРТНЕРЫ</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ ПАРТНЕРА</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="8" style="padding: 10px;">
                        <div style="font:10pt Verdana;">Добавить нового партнера</div>
                        <div class="silver">Поля отмеченные <span class="required">*</span> обязательны к заполнению</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none" width="100%">
                                <tr>
                                    <td align="right">Название<span class="required">*</span></td>
                                    <td style="width: 630px"><input type="text" style="width: 100%"name="partner_name"></td>
                                    <td style="vertical-align:middle;width:85px" rowspan="5"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Отображать на сайте</td>
                                    <td><input type="checkbox" name="show"/></td>
                                </tr>
                                <tr>
                                    <td align="right">Описание<span class="required">*</span></td>
                                    <td style="width: 350px"><textarea rows=3 style="width: 100%"name="partner_des"></textarea></td>
                                </tr>
                                <tr>
                                    <td align="right">Картинка<span class="required">*</span>
                                        <div class="silver">Изображение размером 180*51рх</div></td>
                                    <td style="width: 350px"><input type="file" style="width: 100%"name="partner_img">
                                                       <input type="hidden" name="partner_img_val">
                                        <img id="id_img_edit" style="display:none"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">Ссылка</td>
                                    <td style="width: 350px"><input type="text" style="width: 100%"name="partner_link" value="http://"></td>

                                </tr>
                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($partner)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Описание</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Картинка</td>
                        <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Ссылка</td>
                        <td style="width:30px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                        <td style="width:30px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                        <td style="width:30px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                    </tr>
                    <?foreach($partner as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>
                        <td><?echo $cat['des'];?></td>
                        <td><img src="/img/partners/<?echo $cat['img'];?>"/></td>
                        <td><?echo $cat['link'];?></td>
                        <td><img src="img/admin/<?=($cat['show'])?"item_show.png":"item_hide.png"?>" title="<?=($cat['show'])?"Отображается":"Скрыт"?>"></td>
                        <td><img src="img/admin/b_edit.png" data-id ="<?=$cat['id']?>" data-name="<?echo $cat['name']?>" title="Редактировать" style="cursor: pointer" class="edit"></td>
                        <td><img src="img/admin/b_drop.png" data-id ="<?=$cat['id']?>" title="Удалить" style="cursor: pointer" class="del"></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент партнеров нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>