<?
$root = $_SERVER['DOCUMENT_ROOT'];
require_once $root."/lib/class.invis.db.php";
$db = db :: getInstance();
?>
<tr>
    <td>
        <div class="title">Постоянные скидки</div>
        <fieldset>
                <table align="center" style="width:100%;">
                    <tr>
                        <td style="width:50%; height: 25px; vertical-align:middle; font-weight: bold;">Ночная скидка</td>
                        <td style="width:50%; height: 25px; vertical-align:middle; font-weight: bold;">Скидка выходного дня</td>
                    </tr>
                    <tr>
                        <td>
                            <form name="night_discount" method="POST">
                                <div style="margin-bottom: 3px;margin-top: 16px;font-size: 15px;">Начало действия скидки</div>
                                <?
                                $sql = "SELECT time_start FROM night_discount";
                                $db->query($sql);
                                if($db->getCount()>0){
                                    $t = explode(':',$db->getValue());
                                }
                                else{
                                    $t = '&nbsp;';
                                }
                                ?>

                                <div>
                                <select name="hours_start">
                                    <?
                                    for($i = 0; $i<=23; $i++){
                                        if($i<10){
                                            $i = '0'.$i;
                                        }
                                        $selected = ($t[0] == $i)?' selected':'';
                                        echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                    }
                                    ?>
                                </select>
                                часов
                                <select name="minutes_start">
                                    <?
                                    for($i = 0; $i<60; $i +=15){
                                        if($i<10){
                                            $i = '0'.$i;
                                        }
                                        $selected = ($t[1] == $i)?' selected':'';
                                        echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                    }
                                    ?>
                                </select>
                                минут
                                </div>

                                <div style="margin-bottom: 3px;margin-top: 16px;font-size: 15px;">Окончание действия скидки</div>
                                <?
                                $sql = "SELECT time_end FROM night_discount";
                                $db->query($sql);
                                if($db->getCount()>0){
                                    $t = explode(':',$db->getValue());
                                }
                                else{
                                    $t = '&nbsp;';
                                }
                                ?>
                                <div>
                                    <select name="hours_end">
                                        <?
                                        for($i = 0; $i<=23; $i++){
                                            if($i<10){
                                                $i = '0'.$i;
                                            }
                                            $selected = ($t[0] == $i)?' selected':'';
                                            echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                        }
                                        ?>
                                    </select>
                                    часов
                                    <select name="minutes_end">
                                        <?
                                            for($i = 0; $i<60; $i +=15){
                                                if($i<10){
                                                    $i = '0'.$i;
                                                }
                                                $selected = ($t[1] == $i)?' selected':'';
                                                echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                                            }
                                        ?>
                                    </select>
                                    минут
                                </div>
                                <div style="margin-bottom: 3px;margin-top: 16px;font-size: 15px;">
                                    Размер скидки (целое число от 0 до 100)
                                </div>
                                <?
                                $sql = "SELECT percent FROM night_discount";
                                $db->query($sql);
                                if($db->getCount()>0){
                                    $a = $db->getValue();
                                }
                                else{
                                    $a = '';
                                }
                                ?>
                                <div>
                                    <input type="text" name="percent" style="width:40px;" value="<?=$a?>"> %
                                </div>
                                <div>
                                    <input style="margin-top: 20px;width: 120px;height: 32px;font-size: 17px;"type="button" value="Сохранить">
                                </div>
                            </form>
                        </td>
                        <td>
                            <form name="dw_discount" method="post">
                                <div style="margin-bottom: 3px;margin-top: 16px;font-size: 15px;">
                                    Размер скидки (целое число от 0 до 100)
                                </div>
                                <?
                                $sql = "SELECT percent FROM day_of_week_discount";
                                $db->query($sql);
                                if($db->getCount()>0){
                                    $a = $db->getValue();
                                    }
                                else{
                                    $a = '';
                                    }
                                ?>
                                <div>
                                    <input type="text" name="percent" style="width:40px" value="<?=$a?>"> %
                                </div>
                                <div>
                                    <input style="margin-top: 20px;width: 120px;height: 32px;font-size: 17px;" type="button" value="Сохранить">
                                </div>
                            </form>
                        </td>
                    </tr>
                </table>
        </fieldset>
    </td>
</tr>