<?
require_once "class.invis.db.php";
require_once "class.db.manager.php";
require_once "class.dll.php";
$page->addScript('views/admin/js/ready_objects.js');
$page->addCss('css/jquery-ui-1.9.1.css');
//require_once $root."/lib/class.category.php";
$db = db::getInstance();
$dm = new db_manager();
$db->query("SELECT * FROM objects WHERE DELETED = 0 ORDER BY id DESC");
$objects = $db->getArray();

//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">Готовые объекты</div>
        <fieldset>
            <a id="add_new" style="cursor: pointer">+ ДОБАВИТЬ ОБЪЕКТ</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="6" style="padding: 10px;">
                        <div style="font:10pt Verdana;">Добавить новый объект</div>
                        <div class="silver">Поля отмеченные <span class="required">*</span> обязательны к заполнению</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none" width="100%">
                                <tr>
                                    <td align="right">Название<span class="required">*</span></td>
                                    <td style="width: 630px"><input type="text" style="width: 100%"name="objects_name"></td>
                                    <td style="vertical-align:middle;width:85px" rowspan="4"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Отображать</td>
                                    <td style="width: 350px"><input type="checkbox" name="show" /></td>

                                </tr>
                                <tr>
                                    <td align="right">Дата<span class="required">*</span></td>
                                    <td style="width: 350px"><input type="text" placeholder="гггг-мм-дд" style="width: 100%"name="objects_date"></td>

                                </tr>

                                <tr>
                                    <td align="right">Изображение<span class="required">*</span>
                                        <div class="silver">Изображение должно быть не менее 330px</div></td>
                                    <td style="width: 350px"><input type="file" style="width: 100%"name="objects_img">
                                        <input type="hidden" name="objects_img_val">
                                        <img id="id_img_edit_img" style="display:none"/>
                                    </td>

                                </tr>


                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($objects)>0)
                {?>
                    <tr>
                        <td style="width:15px;">№</td>
                        <td style="height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                        <td style="width:150px; height: 25px; vertical-align:middle; font-weight: bold;">Дата</td>
                        <td style="width:110px; height: 25px; vertical-align:middle; font-weight: bold;">Изображение</td>
                        <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                        <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                        <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                    </tr>
                    <?foreach($objects as $cat){?>
                    <tr>
                        <td><?echo $cat['id'];?></td>
                        <td><?echo $cat['name'];?></td>
                        <td><?echo $DLL->getRusDate($cat['objectDate'])?></td>

                        <td><img  src="/img/objects/m_<?echo $cat['img'];?>"/></td>
                        <td><img src="img/admin/<?=($cat['show'])?"item_show.png":"item_hide.png"?>" title="<?=($cat['show'])?"Отображается":"Скрыт"?>"></td>
                        <td><img src="img/admin/b_edit.png" data-id ="<?=$cat['id']?>" title="Редактировать" style="cursor: pointer" class="edit"></td>
                        <td><img src="img/admin/b_drop.png" data-id ="<?=$cat['id']?>" title="Удалить" style="cursor: pointer" class="del"></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент готовых объектов нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>