<?
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
$page->addScript('views/admin/js/categories.js');
//require_once $root."/lib/class.category.php";
$dm = new db_manager();
$cats = $dm->getAllCategories();
//print_r($cats);
//phpinfo();
?>
<tr>
    <td style="height:75px">
        <div class="title">Категории</div>
        <fieldset>
            <a id="add_cat" style="cursor: pointer">+ ДОБАВИТЬ КАТЕГОРИЮ</a>
        </fieldset>
    </td>
</tr>

<tr>
    <td>
        <fieldset>
            <table align="center" style="width:100%">
                <tr id="form" style="display:none;" >
                    <td colspan="6" style="padding: 10px;">
                        <div style="font:10pt Verdana;">Добавление новой категории</div>
                        <div class="silver">Поля отмеченные <span class="required">*</span> обязательны к заполнению</div>
                        <form method="post">
                            <input type="hidden" name="id" value="">
                            <table align="center" border="none" width="100%">
                                <tr>
                                    <td align="right">Название<span class="required">*</span></td>
                                    <td style="width: 630px"><input type="text" style="width: 100%"name="category_name"></td>
                                    <td style="vertical-align:middle" rowspan="4"><button type="button" name="save">Сохранить</button> </td>
                                </tr>
                                <tr>
                                    <td align="right">Родительская категория</td>
                                    <td style="width: 630px"><?echo $dm->getCategorySelect('parent_id')?></td>
                                </tr>
                                <tr class="forParent">
                                    <td align="right">Колонка меню</td>
                                    <td style="width: 350px"><select name="col">
                                            <?for($i=1;$i<=3;$i++){?>
                                                <option value="<?=$i?>"><?=$i?></option>
                                            <?}?>
                                    </select></td>
                                </tr>
                                <tr class="forParent">
                                    <td align="right">Строка меню</td>
                                    <td style="width: 350px"><select name="row">
                                            <?for($i=1;$i<=10;$i++){?>
                                            <option value="<?=$i?>"><?=$i?></option>
                                            <?}?>
                                    </select></td>
                                </tr>
                            </table>
                        </form>
                    </td>
                </tr>

                <?
                if(count($cats)>0)
                {?>
                <tr>
                    <td style="width:15px;">№</td>
                    <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Название</td>
                    <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">ЧПУ</td>
                    <td style="width:200px; height: 25px; vertical-align:middle; font-weight: bold;">Родительская категория</td>
                    <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                    <td style="width:20px; height: 25px; vertical-align:middle; font-weight: bold;"></td>
                </tr>
                <?foreach($cats as $cat){?>
                    <tr>
                        <td><?echo $cat->get_id();?></td>
                        <td><?echo $cat->get_name();?></td>
                        <td><?echo $cat->get_link();?></td>
                        <td><?echo $dm->getCategoryName($cat->get_parent_id());?></td>
                        <td><img src="img/admin/b_edit.png" data-id="<?echo $cat->get_id();?>" title="Редактировать" style="cursor: pointer" class="edit"></td>
                        <td><img src="img/admin/b_drop.png" data-id="<?echo $cat->get_id();?>" title="Удалить" style="cursor: pointer" class="del"></td>
                    </tr>
                <?}?>



                <?}
                else
                {
                    echo '<tr><td colspan="5" align="center">На данный момент категорий нет</td></tr>';
                }


                ?>


            </table>
        </fieldset>
    </td>
</tr>


