<div class="clr"></div>

<div class="substrate-footer"></div>
</div>
</div>

</div>

<div class=" footer_all">
    <div class="w_1024">
            <div class="w_980">
                            <div class="clr"></div>
                            <div class=" w_980 footer_a">
                                <div class="f_b no_mar_left foot_block1">
                                    <div class="href_hover">
                                    <a href="/delivery" href="" class=" href_1 block_1"></a>
                                    <a href="/delivery" class="title">Оплата</a>
                                        </div>
                                            <div class="text">
                                                Наличный и безналичный расчет
                                                Наложенный платеж
                                            </div>
                                </div>
                                <div class="f_b foot_block2">
                                    <div class="href_hover">
                                    <a href="/delivery#deliv" class="href_1 block_2"></a>
                                    <a href="/delivery#deliv" class="title">Доставка</a>
                                    </div>
                                    <div class="text">
                                        Мы помогаем организовать доставку материалов до места назначения.
                                    </div>

                                </div>
                                <div class="f_b  foot_block2">
                                    <div class="href_hover">
                                    <a href="/reviews" class=" href_1 block_3"></a>
                                    <a href="/reviews" class="title">Отзывы</a>
                                    </div>
                                    <div class="text">
                                        Вы можете прочитать отзывы наших клиентов , а также оставить свой.
                                    </div>

                                </div>
                            </div>

                            <div class="clr"></div>
            </div>
    </div>


    <div class="footer_60">
        <div class="w_1024" style="
    background: #333333 !important;
">
            <div class="w_980">
                    <div class="vert_al footer_bot1">
                        <div class="f_l ">
                            83004, Донецк, ул. Тренева 1
                        </div>
                    </div>
                    <div class="vert_al footer_bot2">
                        <div class="f_l ">
                           <p><span>+380</span> <span>(97</span>) <span>311</span>-<span>03-63</span></p>
                            <p>+380 (62) 387-58-61</p>
                        </div>
                    </div>
                    <div class="vert_al footer_bot3">
                        <div class="f_l ">
                            start-stroy@ukr.net
                        </div>
                    </div>
                    <div class="vert_al footer_bot4">
                        <div class="f_l ">
                            Пн-Пт с 9:00 до 18:00,<br>
                            Сб с 9:00 до 16:00. Вс - выходной
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="w_1024">
    <div class="w_980 footer_bottom">
        <div class="f_r"><a href="/contact">Наши контакты</a> </div>
    <div class="f_l">© 2013 ООО “Старт-Строй”</div>
    <div class="center">
        <div class="soc">


            <div  class="soc_block google">
                <!-- Place this tag where you want the +1 button to render. -->
                <div class="g-plusone" data-size="medium"></div>
                </div>

            <div  class="soc_block odno">
                <div id="ok_shareWidget"></div>
                <script>
                    !function (d, id, did, st) {
                        var js = d.createElement("script");
                        js.src = "http://connect.ok.ru/connect.js";
                        js.onload = js.onreadystatechange = function () {
                            if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
                                if (!this.executed) {
                                    this.executed = true;
                                    setTimeout(function () {
                                        OK.CONNECT.insertShareWidget(id,did,st);
                                    }, 0);
                                }
                            }};
                        d.documentElement.appendChild(js);
                    }(document,"ok_shareWidget","http://start-stroy.com.ua/ ","{width:100,height:30,st:'rounded',sz:20,nt:1}");
                </script>

            </div>
            <div class="soc_block fb">
                <div class="fb-like" data-href="http://start-stroy.com.ua/ " data-width="450" data-layout="button_count" data-show-faces="true" data-send="false"></div>
                </div>
            <div class="soc_block vk">

                <!-- Put this div tag to the place, where the Like block will be -->
                <div id="vk_like"></div>
                <script type="text/javascript">
                    VK.Widgets.Like("vk_like", {type: "mini"});
                </script>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

<script>
    $(document).ready(function()
    {
        $('.href_hover ').hover(
            function() {

                $(this).find('a').css({color:'#e21e23',backgroundPosition:' left bottom'})
            },
            function() {
                $(this).find('a').removeAttr('style')
            }
        );



    })
</script>


<!-- Поместите этот тег за последним тегом виджета кнопка +1. -->
<!--script type="text/javascript">
    window.___gcfg = {lang: 'ru'};

    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script-->