<div class="clr"></div>

<div class="substrate-footer"></div>
</div>
</div>

</div>

<div class=" footer_all">
            <div class="w_980">


                            <div class="clr"></div>



                            <div class=" w_980 footer_a">
                                <div class="f_b no_mar_left foot_block1">
                                    <div class="href_hover">
                                    <a href="/delivery" href="" class=" href_1 block_1"></a>
                                    <a href="/delivery" class="title">Оплата</a>
                                        </div>


                                            <div class="text">
                                                Наличный и безналичный расчет
                                                Наложенный платеж
                                            </div>


                                </div>
                                <div class="f_b foot_block2">
                                    <div class="href_hover">
                                    <a href="/delivery#deliv" class="href_1 block_2"></a>
                                    <a href="/delivery#deliv" class="title">Доставка</a>
                                    </div>
                                    <div class="text">
                                        Мы помогаем организовать доставку материалов до места назначения.
                                    </div>

                                </div>
                                <div class="f_b  foot_block2">
                                    <div class="href_hover">
                                    <a href="/reviews" class=" href_1 block_3"></a>
                                    <a href="/reviews" class="title">Отзывы</a>
                                    </div>
                                    <div class="text">
                                        Вы можете прочитать отзывы наших клиентов , а также оставить свой.
                                    </div>

                                </div>
                            </div>

                            <div class="clr"></div>
            </div>


    <div class="footer_60">
<div class="w_980">
        <div class="vert_al footer_bot1">
            <div class="f_l ">
                83004, Донецк, ул. Тренева 1
            </div>
        </div>
        <div class="vert_al footer_bot2">
            <div class="f_l ">
                +380 (97) 311-03-63<br>
                +380 (62) 387-58-61
            </div>
        </div>
        <div class="vert_al footer_bot3">
            <div class="f_l ">
                start-stroy@ukr.net
            </div>
        </div>
        <div class="vert_al footer_bot4">
            <div class="f_l ">
                Пн-Пт с 9:00 до 18:00,<br>
                Сб с 9:00 до 16:00. Вс - выходной
            </div>
        </div>
</div>
    </div>
    <div class="w_980 footer_bottom">
        <div class="f_r"><a href="/contact">Наши контакты</a> </div>
    <div class="f_l">© 2013 ООО “Старт-Строй”</div>
    <div class="center">
        <div class="soc">
                <!--div class="g-plusone" data-size="medium"></div-->
        </div>
    </div>
    </div>

</div>

<script>
    $(document).ready(function()
    {



        $('.href_hover ').hover(
            function() {

                $(this).find('a').css({color:'#e21e23',backgroundPosition:' left bottom'})

            },
            function() {

                $(this).find('a').removeAttr('style')

            }
        );



    })
</script>


<!-- Поместите этот тег за последним тегом виджета кнопка +1. -->
<!--script type="text/javascript">
    window.___gcfg = {lang: 'ru'};

    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script-->