<?

	$page -> addScript('js/jquery-1.8.2.js','js/jquery-ui_1.9.1.js', 'js/mask.js');
    $page -> addCss('css/reset.css','css/jquery-ui-1.8.16.custom.css','css/style.css','http://fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,cyrillic');


      $page -> setFavicon('/img/favicon.ico');
$bUrl = "http://".$_SERVER['SERVER_NAME'].'/';
require_once "class.invis.db.php";
$db = db::getInstance();
?>




<div class="all_page">
<div class="w_1024 ">
    <div class="w_980">

      <div class="head">
        <a href="/" class="logo"></a>
        <div class="menu_top">
            <div class="p">
                <a href="/catalog/">Каталог</a>
                 <div class="Submenu">
                     <div class="border_top">
                         <?$db-> query("SELECT c.name, c.id AS cname, c.col, c.row, c.link
                                        FROM products AS p, categories AS c
                                        WHERE c.id = p.category_id
                                        AND c.deleted =0
                                        AND p.deleted =0
                                        AND p.`show` = 1
                                        GROUP BY c.id
                                        ORDER BY c.col ASC, c.row ASC");
                         $menu = $db->getArray();
                         if($menu){
                         $col=$menu[0]['col'];
                         $first=true;?>
                         <div class="f_l <?=($menu[0]['col']>1)?"mar_left_28":""?>">
                         <?$row=100;
                         foreach($menu as $item){
                             if($item['col']!=$col){?>
                                 </div>
                                 <div class="f_l <?=($item['col']>1)?"mar_left_28":""?>">
                                 <?$col = $item['col'];
                                 $first = true;
                             }     ?>


                             <a href="/catalog/p/<?=$item['link']?>" class="<?=(!$first)?"mar_top_15":""?> title"><?=$item['name']?></a>

                                <?
                                $first=false;
                                $db->query("SELECT c.name, c.id AS cname, c.link
                                        FROM products AS p, categories AS c
                                        WHERE c.id = p.subCategory_id
                                        AND c.parent_id = {$item['cname']}
                                        AND c.deleted =0
                                        AND p.deleted =0
                                        AND p.`show` = 1
                                        GROUP BY c.id");
                                $subMenu = $db->getArray();
                                foreach($subMenu as $subItem){?>
                             <a href="/catalog/p/<?=$item['link']?>/<?=$subItem['link']?>"><?=$subItem['name']?></a>
                             <?}?>
                             <div class="clr"></div>

                         <?}}?>
                         </div>
                     </div>
                 </div>
            </div>

            <div class="p">
                <a href="/completeobject">Готовые объекты</a>

            </div>
                <a href="/about">О нас  </a>
                <a href="/article">Статьи</a>
                <a href="/partners">Партнеры   </a>
                <a href="/reviews">Отзывы </a>
            </ul>
        </div>
        <div class="f_r contact_top">
           <p>+380 (95) 384-89-99</p>
            <p> +380 (66) 908-66-63</p>
            <a href="/contact" class="text">Наши контакты</a>
        </div>
          <div class="clr"></div>
      </div>
        <div class="clr"></div>

        <!-- Put this script tag to the <head> of your page -->
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?101"></script>

        <script type="text/javascript">
            VK.init({apiId: API_ID, onlyWidgets: true});
        </script>
        <!-- Place this tag in your head or just before your close body tag. -->
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
            {lang: 'uk'}
        </script>

        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>


        <!-- Put this script tag to the <head> of your page -->
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?101"></script>

        <script type="text/javascript">
            VK.init({apiId: 3870061, onlyWidgets: true});
        </script>



 <!--script>
     $( document ).ready(function() {
         w_width=$(window).width()


         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         console.log(w_width)

     })
     $(window).bind('resize',function(){
         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         else
         {
             $('.no_scroll').css({position:'relative',left:'0'})
         }
         w_width=$(window).width()
         console.log(w_width)



     });
 </script-->

