<?

	$page -> addScript('js/jquery-1.8.2.js','js/jquery-ui_1.9.1.js','js/review.js');
    $page -> addCss('css/reset.css','css/style.css','http://fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,cyrillic');


      $page -> setFavicon('/img/favicon.ico');
$bUrl = "http://".$_SERVER['SERVER_NAME'].'/';
?>


<div class="all_page">
<div class="w_1024 ">
    <div class="w_980">

      <div class="head">
        <a href="/" class="logo"></a>
        <div class="menu_top">
            <div class="p">
                <a>Каталог</a>
                 <div class="Submenu">
                     <div class="border_top">
                         <div class="f_l">
                             <a href="/catalog" class="title">Стеновые материалы</a>
                             <a href="/catalog/Product">Газобетон ЮДК</a>
                             <a>Керамические блоки Кератерм </a>
                             <a>Клинкерный кирпич Керамейя</a>
                             <div class="clr"></div>
                             <a class=" mar_top_15 title">Ландшафтные материалы</a>

                             <a>Клинкерная брусчатка Керамейя</a>
                             <a>плитка ФЭМ</a>
                         </div>
                         <div class=" mar_left_28 f_l">
                             <a class="title">Кровельные материалы</a>
                             <a>Битумная черепица IKO</a>
                             <a>Керамическая черепица  Braas</a>
                             <a>Натуральная черепица Braas, Аляска</a>
                             <a>Композитная черепица Metrotile</a>
                             <a>Металическая черепица RUUKKI</a>

                         </div>
                         <div class=" mar_left_28 f_l">
                             <a class="title">Фасадные материалы</a>
                             <a>Фасадная штукатурка</a>
                             <a>Сухие смеси Kreisel</a>
                             <a>Клинкерная плитка </a>
                             <div class="clr"></div>
                             <a class=" mar_top_15 title">Утеплители</a>
                             <a>Минеральная вата</a>
                             <a>Пенопласт</a>
                             <a>Экструдированный пенополистерол</a>
                         </div>
                     </div>
                 </div>
            </div>

            <div class="p">
                <a href="/completeobject">Готовые объекты</a>

            </div>
                <a href="/about">О нас  </a>
                <a href="/article">Статьи</a>
                <a href="/partners">Партнеры   </a>
                <a href="/reviews">Отзывы </a>
            </ul>
        </div>
        <div class="f_r contact_top">
           <p>+380 (95) 384-89-99</p>
            <p> +380 (66) 908-66-63</p>
            <a href="/contact" class="text">Наши контакты</a>
        </div>
          <div class="clr"></div>
      </div>
        <div class="clr"></div>

 <!--script>
     $( document ).ready(function() {
         w_width=$(window).width()


         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         console.log(w_width)

     })
     $(window).bind('resize',function(){
         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         else
         {
             $('.no_scroll').css({position:'relative',left:'0'})
         }
         w_width=$(window).width()
         console.log(w_width)



     });
 </script-->

