<?

	$page -> addScript('js/jquery-1.8.2.js','js/jquery-ui_1.9.1.js', 'js/mask.js');
    $page -> addCss('css/reset.css','css/jquery-ui-1.8.16.custom.css','css/style.css','http://fonts.googleapis.com/css?family=Open+Sans:400,300&subset=latin,cyrillic');


      $page -> setFavicon('/img/favicon.ico');
$bUrl = "http://".$_SERVER['SERVER_NAME'].'/';
require_once "class.invis.db.php";
$db = db::getInstance();
?>


<div class="all_page">
<div class="w_1024 ">
    <div class="w_980">

      <div class="head">
        <a href="/" class="logo"></a>
        <div class="menu_top">
            <div class="p">
                <a href="/catalog/">Каталог</a>
                 <div class="Submenu">
                     <div class="border_top">
                         <?$db-> query("SELECT id,name,link,col,row FROM categories WHERE parent_id = 0 AND deleted=0 ORDER BY col ASC, row ASC");
                         $menu = $db->getArray();
                         $col=1;
                         foreach($menu as $item){
                             if($item['col']!=$col){
                                 echo '</div>';
                                 $col = $item['col'];
                             }
                             if($item['row']==1){
                             ?>
                         <div class="f_l <?=($item['col']>1)?"mar_left_28":""?>">
                             <?}?>
                             <a href="/catalog/p/<?=$item['link']?>" class="<?=($item['row']>1)?"mar_top_15":""?> title"><?=$item['name']?></a>
                                <?$db->query("SELECT name,link FROM categories WHERE parent_id = {$item['id']} AND deleted=0 ");
                                $subMenu = $db->getArray();
                                foreach($subMenu as $subItem){?>
                             <a href="/catalog/p/<?=$item['link']?>/<?=$subItem['link']?>"><?=$subItem['name']?></a>
                             <?}?>
                             <div class="clr"></div>

                         <?}?>
                         </div>
                     </div>
                 </div>
            </div>

            <div class="p">
                <a href="/completeobject">Готовые объекты</a>

            </div>
                <a href="/about">О нас  </a>
                <a href="/article">Статьи</a>
                <a href="/partners">Партнеры   </a>
                <a href="/reviews">Отзывы </a>
            </ul>
        </div>
        <div class="f_r contact_top">
           <p>+380 (95) 384-89-99</p>
            <p> +380 (66) 908-66-63</p>
            <a href="/contact" class="text">Наши контакты</a>
        </div>
          <div class="clr"></div>
      </div>
        <div class="clr"></div>

 <!--script>
     $( document ).ready(function() {
         w_width=$(window).width()


         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         console.log(w_width)

     })
     $(window).bind('resize',function(){
         if (w_width <1024)
         {
             $('.no_scroll').css({position:'relative',left:'-15px'})
         }
         else
         {
             $('.no_scroll').css({position:'relative',left:'0'})
         }
         w_width=$(window).width()
         console.log(w_width)



     });
 </script-->

