<?
    $page -> setTitle("Start stroy");
    $id = $controller->getParam(1);
    require_once 'class.article.php';
    $art = new article($id);

?>
        <h1 >Статьи</h1>
<div class="more_margin article_more">


    <div class="title_page"><span><?echo $art->get_name()?></span></div>
    <div class="date_text"><? echo date('d.m.Y',strtotime($art->get_dateCreate()))?></div>
    <div class="img_more">
        <div class="vert_al">

            <img src="../img/articles/<? echo $art->get_img()?>"/>
        </div>
    </div>

    <div class="text">
        <? echo $art->get_text()?>

    </div>


</div>  <div class="navigate_arrow">
        <a href="/" class=" f_l">Предыдущая статья</a>
        <a href="/" class=" f_r">Следующая статья</a>

    </div>

<div class="clr"></div>
