<?
    $page -> setTitle("Start stroy");

?>
        <h1 >Статьи</h1>
    <div class="page_article">
        <ul>
            <li class="no_mar_left"><a href="article/more">
                    <div class="block_img">
                            <img src="../img/article1.jpg"/>
                    </div>
                <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                            <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.
                           <br><br>
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                </div>
                </a>
            </li>


            <li><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное название </p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.
                            <br><br>
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>
            <li><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>
            <li class="no_mar_left"><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.
                            <br><br>
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>
            <li><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>
            <li><a href="article/more">
                    <div class="block_img">
                    <img src="../img/article1.jpg"/>
                    </div>
                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание   Небольшое описание   Небольшое описание

                        </p>
                    </div>
                </a>
            </li>

            <li class="no_mar_left"><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>
                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.
                            <br><br>
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>


            <li><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное название </p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.
                            <br><br>
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>
            <li><a href="article/more">
                    <div class="block_img">
                        <img src="../img/article1.jpg"/>
                    </div>

                    <div class="more_padding">
                        <p class="name">Достаточное и не слишком длинное название статьи</p>
                        <p class="date">10 июля 2013 г.</p>
                        <div class="clr"></div>
                        <p class="text">
                            Небольшое описание в котором изложенны основные тезисы статьи, размер которого не превышает 4-5 строк.

                        </p>
                    </div>
                </a>
            </li>

        </ul>




    </div>

<div class="clr"></div>


<div class="clr"></div>
<div class="navigate ">



    <a href=""><span class="active">1</span></a>
    <a href=""><span>2</span></a>
    <a href=""><span>3</span></a>
    <a href=""><span>4</span></a>
    <a href=""><span>5</span></a>

</div>
<div class="clr"></div>
<script>
    $( document ).ready(function() {

        $('.page_article ul li a').hover(
            function() {


                var height = $(this).find('.more_padding').height()

               $(this).find('.more_padding').stop().animate({top:300-height},500)
                $(this).find('.text').stop().animate({opacity:'1'},500)

                $(this).find('img').stop().animate({width:'342',height:'191',left:'-19',top:'-10'},300)
            },
            function() {
                $(this).find('.more_padding').stop().animate({top:'174px'},500)
                $(this).find('.text').stop().animate({opacity:'0'},500)
                $(this).find('img').stop().animate({width:'311',height:'174',left:'0',top:'0'},300)

            }
        );


    })

</script>