<?
    $page -> setTitle("Start stroy");
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
$aPage = ($controller->getParam(1))?$controller->getParam(1):1;
$db = db::getInstance();
$dm = new db_manager();
$perPage = 6;
$articles = $dm->getAllArticles(($aPage-1)*$perPage,$perPage);
$db->query("SELECT COUNT(id) FROM articles WHERE `show` = 1 AND deleted=0 ");
$aCount = $db->getValue();

if (count($articles) > 0)
{

?>
        <h1 >Статьи</h1>
    <div class="page_article">
        <ul>



                <?$i=1;
                foreach($articles as $item) {?>
            <li <? echo ($i%3==1)?'class="no_mar_left"':''?>>

                <a href="article/more/<? echo $item->get_id()?>">
                    <div class="block_img">
                        <img src="../img/articles/<?echo (is_file($_SERVER['DOCUMENT_ROOT'].'/img/articles/'.$item->get_thumb()))?$item->get_thumb():'no_prod_min.png';?>"/>
                    </div>
                <div class="more_padding">
                    <p class="name"><? echo $item->get_name()?></p>
                    <?$date = ($item->get_dateCreate()>$item->get_dateUpdate())?$item->get_dateCreate():$item->get_dateUpdate();?>
                    <p class="date"><?echo $DLL->getRusDate($date)?></p>
                    <div class="clr"></div>
                    <p class="text"><? echo $item->get_shortDes()?></p>
                </div>
                    </a>


            </li>
            <?$i++;}?>







        </ul>


        <?}?>

    </div>

<div class="clr"></div>


<div class="clr"></div>
<?if($aCount>$perPage){?>
    <div class="navigate ">


        <?$max = ceil($aCount/$perPage);
        for($i=1;$i<=$max;$i++){
            ?>
            <a href="/article/p/<?=$i?>"><span class="<?=($i == $aPage)?"active":""?>"><?=$i?></span></a>
        <?}?>
    </div>
    <div class="clr"></div>
<?}?>
<script>
    $( document ).ready(function() {

        $('.page_article ul li a').hover(

            function() {


                var height = $(this).find('.more_padding').height()
               if (height <127 )
               {
                   $(this).find('.text').stop().animate({opacity:'1'},200)
                   $(this).find('img').stop().animate({width:'342',height:'191',left:'-19',top:'-10'},300)
                   return false;
               }
               $(this).find('.more_padding').stop().animate({top:300-height},500)
                $(this).find('.text').stop().animate({opacity:'1'},500)

                $(this).find('img').stop().animate({width:'342',height:'191',left:'-19',top:'-10'},300)
            },
            function() {
                $(this).find('.more_padding').stop().animate({top:'174px'},500)
                $(this).find('.text').stop().animate({opacity:'0'},500)
                $(this).find('img').stop().animate({width:'311',height:'174',left:'0',top:'0'},300)

            }
        );


    })

</script>