<?
    $page -> setTitle("Start stroy");
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
$db = db::getInstance();
$dm = new db_manager();
$articles = $dm->getAllArticles();
if (count($articles) > 0)
{

?>
        <h1 >Статьи</h1>
    <div class="page_article">
        <ul>



                <?$i=1;
                foreach($articles as $item) {?>
            <li <? echo ($i%3==1)?'class="no_mar_left"':''?>>

                <a href="article/more">
                    <div class="block_img">
                        <img src="../img/articles/<? echo $item->get_thumb()?>"/>
                    </div>
                <div class="more_padding">
                    <p class="name"><? echo $item->get_name()?></p>
                    <p class="date">10 июля 2013 г.</p>
                    <div class="clr"></div>
                    <p class="text"><? echo $item->get_shortDes()?></p>
                </div>
                    </a>


            </li>
            <?$i++;}?>







        </ul>


        <?}?>

    </div>

<div class="clr"></div>


<div class="clr"></div>
<div class="navigate ">



    <a href=""><span class="active">1</span></a>
    <a href=""><span>2</span></a>
    <a href=""><span>3</span></a>
    <a href=""><span>4</span></a>
    <a href=""><span>5</span></a>

</div>
<div class="clr"></div>
<script>
    $( document ).ready(function() {

        $('.page_article ul li a').hover(
            function() {


                var height = $(this).find('.more_padding').height()

               $(this).find('.more_padding').stop().animate({top:300-height},500)
                $(this).find('.text').stop().animate({opacity:'1'},500)

                $(this).find('img').stop().animate({width:'342',height:'191',left:'-19',top:'-10'},300)
            },
            function() {
                $(this).find('.more_padding').stop().animate({top:'174px'},500)
                $(this).find('.text').stop().animate({opacity:'0'},500)
                $(this).find('img').stop().animate({width:'311',height:'174',left:'0',top:'0'},300)

            }
        );


    })

</script>