<?
    $page -> setTitle("Start stroy");
$page->addScript('js/buy.js','js/jquery.form.js');
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
require_once $root."/lib/class.product.php";
$db = db::getInstance();
$dm = new db_manager();

$id = end(explode('_',$controller->getParam(1)));

$product = new product($id);
?>

<div class="catalog_page buy_page">
<h1 >Заказ товара</h1>

<div class="f_l">

    <ul class="product_ul">


        <li class="no_mar_left">
            <a href="catalog/product/<?=$DLL->linkInBD($product->get_name(),$product->get_id())?>">



            <div class="img"><div><img src="../img/products/m_<?=$product->get_img()?>"/></div></div>
            <div class="text"><?=$product->get_name()?></div>

              <div class="price_block">
                <div class="vert_align">
                    <div class="old_price" <?echo ($product->get_price()==0)?"style='display:none'":""?>  ><? echo $product->get_price()?> грн.</div>
                    <div class="new_price <?echo ($product->get_price()==0)?"":"red"?>"><? echo $product->get_priceForSale()?> грн.</div>
                </div>
              </div>
            </a>

        </li>

    </ul>




</div>

    <div class="buy_block f_l">
        <form name="order" method="post" >
            <input type="hidden" name="prod_id" value="<?=$product->get_id()?>"/>
   <div class="f_l" style="margin-right: 29px">

       <input type="text" name="name"/>
         <p>* Ваше имя:</p>

       <div class="clr"></div>
       <input type="text" name="phone"/>
        <p>* Телефон:</p><br>
       <div class="clr"></div>

       <input type="text" name="email"/>
        <p>E-mail:</p>
       <div class="clr"></div>

   </div>
        <div class="f_l">
            <p style="float: left !important;">Комментарий:</p>
            <div class="clr"></div>
           <textarea name="comment"></textarea>
        </div>

        <div class="clr"></div>
        <div class="buy" id="make_order" style="margin-bottom: 25px;">ЗАКАЗАТЬ</div>
        <div class="text">Заполните форму заказа. Укажите в комментарии количество товара, удобный способ оплаты и доставки. Наш менеджер свяжется с Вами в ближайшее время для уточнения заказа.</div>
        <div class="price_text f_r">Цены на 10,08,2013</div>
        <div class="clr"></div>

   </div>
    </form>
<div class="clr"></div>

</div>