<?
    $page -> setTitle("Start stroy");

?>

<div class="catalog_page buy_page">
<h1 >Заказ товара</h1>

<div class="f_l">

    <ul class="product_ul">


        <li class="no_mar_left">
            <a href="catalog/Product">



            <div class="img"><div><img src="../img/t1.jpg"/></div></div>
            <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

              <div class="price_block">
                <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                </div>
              </div>
            </a>

        </li>

    </ul>




</div>

    <div class="buy_block f_l">
   <div class="f_l" style="margin-right: 29px">
       <input type="text"/>
         <p>* Ваше имя:</p>

       <div class="clr"></div>
       <input type="text"/>
        <p>* Телефон:</p><br>
       <div class="clr"></div>

       <input type="text"/>
        <p>E-mail:</p>
       <div class="clr"></div>

   </div>
        <div class="f_l">
            <p style="float: left !important;">Комментарий:</p>
            <div class="clr"></div>
           <textarea ></textarea>
        </div>

        <div class="clr"></div>
        <div class="buy" style="margin-bottom: 70px;">ЗАКАЗАТЬ</div>
        <div class="text">Заполните форму заказа. Укажите в комментарии количество товара, удобный способ оплаты и доставки. Наш менеджер свяжется с Вами в ближайшее время для уточнения заказа.</div>
        <div class="price_text f_r">Цены на 10,08,2013</div>
        <div class="clr"></div>

   </div>
<div class="clr"></div>

</div>