<?
    $page -> setTitle("Start stroy");

?>

<div class="catalog_page">
<h1 >Каталог продукции</h1>

<div class="trail_href">
      <a href="/">Каталог продукции</a>
      <span></span>
      <p>Стеновые материалы</p>

</div>
    <div class="h_50">
        <div class="title_page f_l"><span>Стеновые материалы</span></div>
        <div class="price_text f_r">Цены на 10.08.2013</div>
    </div>

    <ul class="product_ul">
        <li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">      <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

              <div class="price_block">
                <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                </div>
              </div>
            </a>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height">     <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
                </a>
        </li>
        <li class="">
            <a href="catalog/Product">
                <div class="max_height">    <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
                </a>
        </li>
        <li class="">
            <div class="max_height">     <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">     <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">      <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">        <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">       <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>

        <li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">      <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

                <div class="price_block">
                    <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                    </div>
                </div>
            </a>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height">     <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с</div>

                <div class="price_block">
                    <div class="vert_align">

                        <div class="new_price ">9,50 грн.</div>
                    </div>
                </div>
                <div class="buy">ЗАКАЗАТЬ</div>
            </a>
        </li>
        <li class="">
            <a href="catalog/Product">
                <div class="max_height">    <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

                <div class="price_block">
                    <div class="vert_align">

                        <div class="new_price ">9,50 грн.</div>
                    </div>
                </div>
                <div class="buy">ЗАКАЗАТЬ</div>
            </a>
        </li>
        <li class="">
            <div class="max_height">     <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">     <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">      <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">        <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">       <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
    </ul>

<div class="clr"></div>
<div class="bt_more">ПОКАЗАТЬ ЕЩЕ</div>
</div>
<script>

    $(document).ready(function()
    {





        $('.product_ul li').hover(
            function() {
                $(this).find('img').removeAttr('style')

                var height = $(this).find('img').height();
                var width  = $(this).find('img').width();
                height_old = height;
                width_old = width;
                height = (height*110)/100;
                width = (width*110)/100;

                $(this).find('img').stop().animate({width:width,height:height},300)




            },
            function() {

                $(this).find('img').stop().animate({width:width_old,height:height_old},300)

            }
        );



    })
</script>