<?
    $page -> setTitle("Start stroy");

require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
$db = db::getInstance();
$dm = new db_manager();

$id = $controller->getParam(3);


$db->query("SELECT * FROM products WHERE id = ".$id );
$product = $db->getRow();
$db->query("SELECT * FROM characteristics WHERE product_id = ".$id);
$char = $db->getArray();
?>






<div class="catalog_page tovar_page ">
<h1 >Каталог продукции</h1>

<div class="trail_href">
      <a href="/">Каталог продукции</a>
      <span></span>
    <a href="/<?echo $dm->getCategory_link($product['category_id']);?>"><?echo $dm->getCategoryName($product['category_id']);?></a>
        <span></span>
        <a href="/<?echo $dm->getCategory_link($product['category_id']);?>"> <? echo $dm->getSubCategory_name($product['subCategory_id'])?> </a>
    <span></span>
    <p><?echo $product['name'];?></p>
</div>
    <div class="h_50">
        <div class="title_page f_l"><span><?echo $product['name'];?></span></div>

    </div>

   <div class="img_tovar">
      <div><img src="../img/products/<?echo $product['img'];?>"/></div>
   </div>
    <div class="tovar_text">
        <p class="title">Тип материала: <? echo $dm->getMaterialName($product['material_id'])?></p>
        <p class="title2">Производитель: <? echo $dm->getFirmName($product['firm_id'])?></p>
        <p><? echo $product['des']?></p>

        <div class="price">
            <p class="text">Стоимость за единицу</p>
            <p class="text_right">Цены на 10.08.2013</p>
<br>
            <p class="proce_old"  <?echo ($product['price']==0)?"style='display:none'":""?>   ><? echo $product['price']?> грн.</p>
            <p class="proce_new  <?echo ($product['price']==0)?"":"red"?>"><? echo $product['priceForSale']?> грн.</p>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
        </div>
    </div>


<div class="clr"></div>

    <?if (count($char) > 0)
    {?>
<div class="title_char"><span>Характеристика</span> товара</div>
                <table class="charact">
                          <?  if (count($char) >0 )
                            {
                                    for($i=1;$i<=count($char);$i++)
                                    {
                                             echo ' <tr> <td class="left"> ';
                                                 echo $char[$i-1]['name'] ;
                                             echo ' </td>  <td class="right">';
                                                 echo  $char[$i-1]['value'];
                                             echo '  </td>  </tr>';

                                    }
                            }?>

                </table>


<?}?>
</div>