<?
    $page -> setTitle("Start stroy");

require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
require_once $root."/lib/class.product.php";
$db = db::getInstance();
$dm = new db_manager();

$id = end(explode('_',$controller->getParam(1)));

$product = new product($id);
$db->query("SELECT * FROM characteristics WHERE product_id = ".$id);
$char = $db->getArray();
?>






<div class="catalog_page tovar_page ">
<h1 >Каталог продукции</h1>

<div class="trail_href">
      <a href="/catalog/">Каталог продукции</a>
      <span></span>
    <a href="/catalog/p/<?echo $dm->getCategory_link($product->get_category_id());?>"><?echo $dm->getCategoryName($product->get_category_id());?></a>
        <span></span>
        <a href="/catalog/p/<?echo $dm->getCategory_link($product->get_category_id());?>/<?echo $dm->getCategory_link($product->get_subCategory_id());?>"> <? echo $dm->getSubCategory_name($product->get_subCategory_id())?> </a>
   <!--span></span>
    <p><?echo $product->get_name();?></p-->
</div>
    <div class="h_50">
        <div class="title_page f_l"><span><?echo $product->get_name();?></span></div>

    </div>

   <div class="img_tovar">
      <div><img src="../img/products/<?echo $product->get_img();?>"/></div>
   </div>
    <div class="tovar_text">
        <p class="title">Тип материала: <? echo $dm->getMaterialName($product->get_material_id())?></p>
        <p class="title2">Производитель: <? echo $dm->getFirmName($product->get_firm_id())?></p>
        <p><? echo $product->get_des()?></p>

        <div class="price">
            <p class="text">Стоимость за единицу</p>
            <p class="text_right">Цены на <?=$DLL->getActualDate()?></p>
<br>
            <p class="proce_old"  <?echo ($product->get_price()==0)?"style='display:none'":""?>   ><? echo $product->get_price()?> грн.</p>
            <p class="proce_new  <?echo ($product->get_price()==0)?"":"red"?>"><? echo $product->get_priceForSale()?> грн.</p>
            <a href="/order/p/<?=$DLL->linkInBD($product->get_name(),$product->get_id())?>" class="buy">ЗАКАЗАТЬ</a>
        </div>
    </div>


<div class="clr"></div>

    <?if (count($char) > 0)
    {?>
<div class="title_char"><span>Характеристики</span> товара</div>
                <table class="charact">
                          <?  if (count($char) >0 )
                            {
                                    for($i=1;$i<=count($char);$i++)
                                    {
                                             echo ' <tr> <td class="left"> ';
                                                 echo $char[$i-1]['name'] ;
                                             echo ' </td>  <td class="right">';
                                                 echo  $char[$i-1]['value'];
                                             echo '  </td>  </tr>';

                                    }
                            }?>

                </table>


<?}?>
</div>