<?
    $page -> setTitle("Start stroy");
require_once "class.product.php";
require_once "class.dll.php";
require_once "class.db.manager.php";
$cat_id  = end(explode('_',$_SERVER['REQUEST_URI']));
$perPage = 16;
$dm = new db_manager();
if(!is_numeric($cat_id)){
    $products_obj = $dm->getAllProducts(0,$perPage);
}else{
    $products_obj = $dm->getAllProducts(0,$perPage,$cat_id);
}

if(is_numeric($cat_id)){
$db->query("SELECT name, parent_id FROM categories WHERE id = {$cat_id} ");
$curCat = $db->getRow();
if($curCat['parent_id'] != 0){
    $db->query("SELECT name,link FROM categories WHERE id = {$curCat['parent_id']}");
    $curParCat = $db->getRow();
}

}
?>
<script>
    $(document).ready(function(){
        var from = 0
        var count = 16
        $(document).on('click','.bt_more',function(){
            var th = $(this)
            var max = th.data('max')
            var cat = th.data('cat')
            $.post('/lib/getMoreProducts.php',{from:from, count:count, cat:cat},function(data){
                console.log(data)
                $('.product_ul').append(data)
                if(max>(from+count)){
                    from +=count
                }else{
                    th.hide()
                }

            })

        })
    })

</script>
<div class="catalog_page">
<h1 >Каталог продукции</h1>

<div class="trail_href">
      <a href="/catalog/">Каталог продукции</a>
      <span></span>
<?if($curParCat){?>
    <a href="/catalog/p/<?=$curParCat['link']?>"><?=$curParCat['name']?></a>
    <span></span>
    <?}?>

      <p><?=$curCat['name']?></p>

</div>
    <div class="h_50" style="margin-bottom: 16px;">
        <div class="title_page f_l"><span><?=($curCat['name'])?$curCat['name']:"Каталог продукции"?></span></div>
        <div class="price_text f_r">Цены на <?=$DLL->getActualDate()?></div>
    </div>
<?if($products_obj){
    $k = 1;
?>
    <ul class="product_ul">
    <?foreach($products_obj as $prod){?>
        <li class="<?=($k%4==1)?"no_mar_left":""?>">
            <a href="catalog/product/<?=$DLL->linkInBD($prod->get_name(),$prod->get_id())?>">
                <div class="max_height">      <div class="img"><div><?if(is_file($_SERVER['DOCUMENT_ROOT'].'/img/products/m_'.$prod->get_img())){?><img src="../img/products/m_<? echo $prod->get_img()?>"/><?}?></div></div></div>
            <div class="text"><?=$prod->get_name()?></div>

              <div class="price_block">
                <div class="vert_align">
                    <div class="old_price" <?echo ($prod->get_price()==0)?"style='display:none'":""?>  ><? echo $prod->get_price()?> грн.</div>
                    <div class="new_price <?echo ($prod->get_price()==0)?"":"red"?>"><? echo $prod->get_priceForSale()?> грн.</div>
                </div>
              </div>
            </a>
            <a href="/order/p/<?=$DLL->linkInBD($prod->get_name(),$prod->get_id())?>" class="buy">ЗАКАЗАТЬ</a>
        </li>
        <?$k++;}?>

    </ul>
<?}?>
<div class="clr"></div>
<?
if(is_numeric($cat_id)){
    $sql = "SELECT COUNT(id) as count  FROM products WHERE (category_id={$cat_id} OR subCategory_id={$cat_id}) AND `show` = 1 AND deleted = 0";
}else{
    $sql = "SELECT COUNT(id) as count FROM products WHERE `show` = 1 AND deleted = 0";
}
$db->query($sql);
$count = $db->getValue();
if($count>$perPage){?>
<div class="bt_more" data-from="<?=$perPage?>" data-count="<?=$perPage?>" data-cat="<?=(is_numeric($cat_id))?$cat_id:""?>" data-max="<?=$count?>">ПОКАЗАТЬ ЕЩЕ</div>
<?}?>
</div>
<script>

    $(document).ready(function()
    {





        $('.product_ul li').hover(
            function() {
                $(this).find('img').removeAttr('style')

                var height = $(this).find('img').height();
                var width  = $(this).find('img').width();
                height_old = height;
                width_old = width;
                height = (height*110)/100;
                width = (width*110)/100;

                $(this).find('img').stop().animate({width:width,height:height},300)




            },
            function() {

                $(this).find('img').stop().animate({width:width_old,height:height_old},300)

            }
        );



    })
</script>