<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/jqueryrotate.2.1.js');

?>
<div class="all_circle">
        <div class="circle_main">
            <div id="circle1" data-timeend="590"></div>
            <div id="circle2" data-timeend="590"></div>
            <div id="circle3" data-timeend="590"></div>
            <div id="circle4" data-timeend="590"></div>



        </div>
    <div id="circle_center"></div>
        <div class="images">
            <div class="img_1"><img src="../img/test/yel.png" width="122"/></div>
            <div class="img_2"><img src="../img/test/red.png" width="122"/></div>
            <div class="img_3"><img src="../img/test/blue.png" width="122"/></div>
            <div class="img_4"><img src="../img/test/green.png" width="122"/></div>
        </div>

</div>

<script>
    $(document).ready(function(){

        if (window.devicePixelRatio > 1) {
            var lowresImages = $('img');

            images.each(function(i) {
                var lowres = $(this).attr('src');
                var highres = lowres.replace(".", "@2x.");
                $(this).attr('src', highres);
            });
        }



        $('.images div').css({display:'none'})
        var angle = 45;


        var time=500
        var timeEnd=590

        var step = 1
      setInterval(rotate,10);



        function rotate (){

            time +=1

            if(time>500){
                angle+=step;

                $('.images div').removeAttr('style');

                var tmp = angle%360
                $('.circle_main div').removeClass('active')
                switch(tmp){
                    case 45:
                        $('.images .img_1').fadeIn(500);
                        $('#circle1').addClass('active')

                        break;

                    case 225:
                        $('.images .img_2').fadeIn(500);
                        $('#circle2').addClass('active')
                        break;
                    case 315:
                        $('.images .img_3').fadeIn(500);
                        $('#circle3').addClass('active')
                        break;
                    case 135:
                        $('.images .img_4').fadeIn(500);
                        $('#circle4').addClass('active')
                        break;
                }


                }



            if(time==timeEnd){
                time=0
                timeEnd = 590
                step = 1
            }
           // console.log(angle)
            jQuery(".circle_main").rotate(angle);

        }
        $('.circle_main div').click(function(){

            $('.circle_main div').removeClass('active')
            $(this).addClass('active')
            $('.images div').removeAttr('style');

            var tmp = angle%360


            switch($(this).attr('id')){

                case 'circle1':
                    if(tmp >225)
                    {
                        timeEnd = 500+Math.abs(225-tmp);
                    }
                    else
                    {
                        timeEnd = 500+Math.abs(45-tmp);
                        if(45-tmp == -90){
                            step = -1
                        }
                    }
                    console.log(timeEnd)
                    break;

                case 'circle2': timeEnd = 500+Math.abs(225-tmp);
                    if(225-tmp == -90){
                        step = -1
                    }
                    console.log(tmp)
                    break;

                case 'circle3':
                    if(tmp <= 45)
                    {
                        timeEnd = 500+Math.abs(135-tmp);
                            step = -1
                    }
                    else
                    {
                        timeEnd = 500+Math.abs(315-tmp);
                    }
                    console.log(tmp)
                    break;

                case 'circle4': timeEnd = 500+Math.abs(135-tmp);
                    if(135-tmp == -90){
                        step = -1
                    }
                    console.log(timeEnd)
                    break;
            }
           time = 500

          //  console.log(angle%360)
        })

    })





</script>

