<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/jquery.aw-showcase.js');
$page -> addCss('css/style_slider.css');

?>

<script type="text/javascript">

    $(document).ready(function()
    {
        $("#showcase").awShowcase(
            {
                content_width:			760,
                content_height:			470,
                fit_to_parent:			false,
                auto:					false,
                interval:				3000,
                continuous:				false,
                loading:				true,
                tooltip_width:			200,
                tooltip_icon_width:		32,
                tooltip_icon_height:	32,
                tooltip_offsetx:		18,
                tooltip_offsety:		0,
                arrows:					true,
                buttons:				false,
                btn_numbers:			false,
                keybord_keys:			true,
                mousetrace:				false, /* Trace x and y coordinates for the mouse */
                pauseonover:			true,
                stoponclick:			true,
                transition:				'hslide', /* hslide/vslide/fade */
                transition_delay:		300,
                transition_speed:		500,
                show_caption:			'onhover', /* onload/onhover/show */
                thumbnails:				true,
                thumbnails_position:	'outside-last', /* outside-last/outside-first/inside-last/inside-first */
                thumbnails_direction:	'horizontal', /* vertical/horizontal */
                thumbnails_slidex:		2, /* 0 = auto / 1 = slide one thumbnail / 2 = slide two thumbnails / etc. */
                dynamic_height:			false, /* For dynamic height to work in webkit you need to set the width and height of images in the source. Usually works to only set the dimension of the first slide in the showcase. */
                speed_change:			false, /* Set to true to prevent users from swithing more then one slide at once. */
                viewline:				false /* If set to true content_width, thumbnails, transition and dynamic_height will be disabled. As for dynamic height you need to set the width and height of images in the source. */
            });
    });

</script>

        <h1 >Готовые обьекты</h1>

<div class="page_comlete_object">

<div style="width: 760px; margin: auto;">

    <div id="showcase" class="showcase">

        <div class="showcase-slide">

            <div class="showcase-content">
                <img src="images/Image0054.jpg" alt="01" />

            </div>
            <div class="showcase-thumbnail">
                <img src="images/Image0054.jpg" alt="01" width="140px" />

                <div  class="text">Just some more of this text</div>
            </div>


        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/Image00254.jpg" alt="02" />

            </div>
            <div class="showcase-thumbnail">
                <img src="images/Image00254.jpg" alt="01" width="60px" />


            </div>

        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/03.jpg" alt="03" />
            </div>
            <div class="showcase-thumbnail">
                <img src="images/03.jpg" alt="01" width="140px" />


            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/04.jpg" alt="04" />
            </div>
            <div class="showcase-thumbnail">
                <img src="images/03.jpg" alt="06" width="140px" />
            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/05.jpg" alt="05" />
            </div>
            <div class="showcase-thumbnail">
                <img src="images/03.jpg" alt="06" width="140px" />
            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/06.jpg" alt="06" />
            </div>
            <div class="showcase-thumbnail">
                <img src="images/03.jpg" alt="06" width="140px" />


            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/07.jpg" alt="07" />

            </div>
            <div class="showcase-thumbnail">
                <img src="images/07.jpg" alt="07" width="140px" />

            </div>
        </div>


        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/08.jpg" alt="08" />
            </div>
            <div class="showcase-thumbnail">
                <img src="images/08.jpg" alt="08" width="140px" />
                <div class="text">Just </div>
            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
        <div class="showcase-slide">
            <div class="showcase-content">
                <img src="images/01.jpg" alt="08" />
            </div>

            <div class="showcase-thumbnail">
                <img src="images/01.jpg" alt="08" width="140px" />

            </div>
        </div>
    </div>


    <div class="title">Достаточное и не слишком длинное название объекта</div>
    <div class="date_text">10 июля 2013 г.</div>


</div>
</div>



<div class="clr"></div>


<script>

    $(document).ready(function(){
    $('.showcase-thumbnail-container').hover(function(){

        $('.showcase-thumbnail-horizontal').stop().animate({opacity:'1'},300)
    }, function() {

        $('.showcase-thumbnail-horizontal').stop().animate({opacity:'0'},300)

    });
    })

</script>
<!--script>



        /*
            var text_z =  $('.active .text2').clientHeight


                var code = document.getElementById('code');


            console.log($('.active .text2'))
                document.getElementById('title').innerHTML = text_z
        */
    /*console.log(offset.left)*/
    //    $('.showcase-thumbnail-wrapper-horizontal').animate({left:-(offset.left)})


    $(document).ready(function(){

        var left = 0
        var click = 0
        var left2 = 0
var temp = 0



        $(document).on('click','.showcase-thumbnail',function()
        {
        /*$('.showcase').click(function(){*/

            var offset = $('.active').offset();
            var active_width =  $('.active').width()

            var offset_top = $('.showcase').offset();
            var position  = offset.left - offset_top.left
            var min_pos = 360 - position
            var max_right_numb = ($('.showcase-thumbnail-wrapper-horizontal').width())-760
            var pos_right =(( ($('.showcase-thumbnail-wrapper-horizontal').offset().left)- offset_top.left)-active_width+16)*-1






            /*console.log(position)
            console.log(min_pos)*/
          /*  /$('.showcase-thumbnail-wrapper-horizontal').animate({left:min_pos},300)*/




                if (position >360 )

                {


                    left = left +  ($('.active').width())+16
                    if (max_right_numb < pos_right )
                    {
                      /*  $('.showcase-thumbnail-wrapper-horizontal').css({left:'max_right_numb'})*/
                                          left = max_right_numb
                                            }

                    $('.showcase-thumbnail-wrapper-horizontal').animate({left:-(left)},300)
                    click = 1

                }
                if((position < 360) && (click == 1))
                {

                    left = left -  ($('.active').width())-16



                    var pos_block = $('.showcase-thumbnail-wrapper-horizontal')
                    if ( (parseInt(pos_block.css("left") ))  > 0)
                    {
                        left =0
                    }

                    $('.showcase-thumbnail-wrapper-horizontal').animate({left:-(left)},300)

                }



        })











        var width_block =( $('.showcase-thumbnail-wrapper-horizontal').width())-760;
        var width_chag = width_block/760

        var width_c = 0
       if($('.showcase-thumbnail-wrapper-horizontal').width() >760)
       {/*
           $('.showcase-thumbnail-container').mousemove(function(e){



               var offset = $(this).offset();
              if (e.pageX- offset.left >100)
              { }
                  $('.showcase-thumbnail-wrapper-horizontal').css({left:-(e.pageX- offset.left)*width_chag})





               //   console.log(e.pageX-offset.left)
           }).mouseout(function(){

                   width_c = 0


               });*/
       }



/*
        var block = 0;

        function sec() {
            block = block+1
            $('.showcase-thumbnail-wrapper-horizontal').css({left:-block})
        }


        function sec2() {
            block = block+1
            $('.showcase-thumbnail-wrapper-horizontal').css({left:block})
        }

        $('.rifht_block').hover(   function() {
                intervalID = setInterval(sec,1)


            },
            function() {


                clearInterval(intervalID)

            }
        );



        $('.left_block').hover(   function() {
                intervalID = setInterval(sec2,1)


            },
            function() {


                clearInterval(intervalID)

            }
        );


        console.log(e.pageY)
*/
      /*  $('.showcase-thumbnail').hover(
            function() {


                var height = $(this).find('img').height();
                var width  = $(this).find('img').width();
                height_old = height;
                width_old = width;
                height = (height*110)/100;
                width = (width*110)/100;

                $(this).find('img').stop().animate({width:width,height:height},300)



            },
            function() {

                $(this).find('img').removeAttr("style")
                $(this).find('img').stop().animate({width:width_old,height:height_old},300)

            }
        );*/


    })

</script-->