<?
    $page -> setTitle("Start stroy");
$page -> addScript('http://maps.google.com/maps/api/js?sensor=false');
$page -> addScript('js/way.js');
?>



<div class="page_contact">
    <h1 >Контактная информация</h1>
        <div class="footer_60">

            <div class="vert_al footer_bot1">
                <div class="f_l ">
                    83004, Донецк, ул. Тренева 1
                </div>
            </div>
            <div class="vert_al footer_bot2">
                <div class="f_l ">
                    +380 (97) 311-03-63<br>
                    +380 (62) 387-58-61
                </div>
            </div>
            <div class="vert_al footer_bot3">
                <div class="f_l ">
                    start-stroy@ukr.net
                </div>
            </div>
            <div class="vert_al footer_bot4">
                <div class="f_l ">
                    Пн-Пт с 9:00 до 18:00,<br>
                    Сб с 9:00 до 16:00. Вс - выходной
                </div>
            </div>

        </div>

</div>
</div>


<div id='main' class='way page_contact'>


    <div class='google-map-route'>
        <div class='element a'>
            <input type='text' value='Артема 100, Донецк, Украина, 83000'/>
        </div>
        <div class='element b'>
            <input type='text' readonly='readonly' value='Донецк, ул. Шахтеров Донбасса, 1з' />
        </div>
        <div class='travelling-mode driving selected'></div>
        <div class='travelling-mode walking'></div>
        <div class="button">ПРОЛОЖИТЬ</div>
    </div>

    <div class='clear'></div>
    <div id='map'></div>
</div>

<div class="w_980 page_contact">




        <div class="title_page f_l"><span>Наши</span> сотрудники</div>

        <div class="clr"></div>
        <div class="f_l contact_1">Семенов Юрий</div>
        <div class="f_l contact_2">Семенов Константин</div>
        <div class="f_l contact_3">Корытина Евгения</div>
        <div class="clr"></div>
    <div style="margin-top: 12px;" class="title_page f_l"><span>Наш </span> офис</div>


</div>
<div class="clr"></div>
    <div class="img_1024_cont block_img_1024_about "></div>
<div class="w_980 page_contact">

    <div class="title_page f_l"><span>Образцы</span> продукции и сертификаты</div>

    <div class="clr"></div>
    <div class="f_l contact_1 cont_bot_img_1"></div>
    <div class="f_l contact_2 cont_bot_img_2"></div>
    <div class="f_l contact_3 cont_bot_img_3"></div>
    <div class="clr"></div>
</div>