<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/jquery.slides.js');
$page -> addCss('css/style_slider_main.css');
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";

$db = db::getInstance();
$dm = new db_manager();
$products = $dm->getAllProducts();
$banners = $dm->getAllBanners();
if (count($products) > 0)
{

?>
<style>
    #slides {
        display:none;
    }
</style>
<script>
    $(function(){
        $("#slides").slidesjs({
            width: 1024,
            height: 360,
            navigation:{
                active:false
            },
            play: {
                active: false,
                // [boolean] Generate the play and stop buttons.
                // You cannot use your own buttons. Sorry.
                effect: "slide",
                // [string] Can be either "slide" or "fade".
                interval: 5000,
                // [number] Time spent on each slide in milliseconds.
                auto: true,
                // [boolean] Start playing the slideshow on load.
                swap: true,
                // [boolean] show/hide stop and play buttons
                pauseOnHover: false,
                pause:10,
                // [boolean] pause a playing slideshow on hover
                restartDelay: 2500
                // [number] restart delay on inactive slideshow
            },
           callback: {
                loaded: function(number) {
                    $('.block1').animate({left:50},800)
                    $('.block2').animate({left:50},1000)
                    $('.block3').animate({left:50},1200)
                },
                start: function(number) {
                    $('.block1, .block2, .block3').hide()
                    $('.block1').stop().animate({left:-1000},500)
                    $('.block2').stop().animate({left:-1000},500)
                    $('.block3').stop().animate({left:-1000},500)

                },
                complete: function(number) {
                    $('.block1, .block2, .block3').show()
                    $('.block1').animate({left:50},800)
                    $('.block2').animate({left:50},1000)
                    $('.block3').animate({left:50},1200)
                    console.log(this)
                }
            }
        });
    });
</script>


<div class="clr"></div>
</div>
<div class="slider">
    <div id="container">


        <div id="slides">

            <?$i=1;
            foreach($banners as $item) {?>
                <div>
                    <img src="../img/banner/<?echo $item->get_img()?>" width="1024" height="360">
                    <div class="tex_fly block1 "><?echo $item->get_firstStr()?></div>
                    <? if($item->get_secondStr()!=''){?><div class="tex_fly block2 "><?echo $item->get_secondStr()?></div><?}?>
                    <? if($item->get_thirdStr()!=''){?><div class="tex_fly block3 "><?echo $item->get_thirdStr()?></div><?}?>
                </div>

                <?$i++;}?>

        </div>

    </div>
</div>

<div class="w_980">
    <div class="h_50">
        <div class="title_page f_l"><span>Топ</span> предложения строительных материалов</div>
        <div class="price_text f_r">Цены на <?=$DLL->getActualDate()?></div>
    </div>

    <ul class="product_ul">
    <?$i=1;
    foreach($products as $item) {?>
    <li <? echo ($i%4==1)?'class="no_mar_left"':''?>>
        <a href="catalog/product/<? echo $DLL->linkInBD($item->get_name(),$item->get_id())?>">
            <div class="max_height">   <div class="img"><div><?if(is_file($_SERVER['DOCUMENT_ROOT'].'/img/products/m_'.$item->get_img())){?><img src="../img/products/m_<? echo $item->get_img()?>"/><?}?></div></div></div>
            <div class="text"><? echo $item->get_name()?></div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price" <?echo ($item->get_price()==0)?"style='display:none'":""?>  ><? echo $item->get_price()?> грн.</div>
                    <div class="new_price <?echo ($item->get_price()==0)?"":"red"?>"><? echo $item->get_priceForSale()?> грн.</div>
                </div>
            </div>
            <a href="/buy/p/<? echo $DLL->linkInBD($item->get_name(),$item->get_id())?>" class="buy">ЗАКАЗАТЬ</a>
        </a>
    </li>

        <?$i++;}?>

    </ul>

    <?}?>
