<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/slides.js');
$page -> addCss('css/style_slider_main.css');
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";

$db = db::getInstance();
$dm = new db_manager();
$products = $dm->getAllProducts();
$banners = $dm->getAllBanners();
if (count($products) > 0)
{

?>




<div class="clr"></div>
</div>
<div class="slider">











    <div id="container">


        <div id="slides">

            <?$i=1;
            foreach($banners as $item) {?>
                <div>
                    <img src="../img/banner/<?echo $item->get_img()?>" width="1024" height="360">
                    <div class="tex_fly block1 "><?echo $item->get_firstStr()?></div>
                    <? if($item->get_secondStr()!=''){?><div class="tex_fly block2 "><?echo $item->get_secondStr()?></div><?}?>
                    <? if($item->get_thirdStr()!=''){?><div class="tex_fly block3 "><?echo $item->get_thirdStr()?></div><?}?>
                </div>

                <?$i++;}?>

        </div>

    </div>
</div>

<div class="w_980">
    <div class="h_50">
        <div class="title_page f_l"><span>Топ</span> предложения строительных материалов</div>
        <div class="price_text f_r">Цены на <?=$DLL->getActualDate()?></div>
    </div>

    <ul class="product_ul">
    <?$i=1;
    foreach($products as $item) {?>
    <li <? echo ($i%4==1)?'class="no_mar_left"':''?>>
        <a href="catalog/product/<? echo $DLL->linkInBD($item->get_name(),$item->get_id())?>">
            <div class="max_height">   <div class="img"><div><img src="../img/products/m_<? echo $item->get_img()?>"/></div></div></div>
            <div class="text"><? echo $item->get_name()?></div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price" <?echo ($item->get_price()==0)?"style='display:none'":""?>  ><? echo $item->get_price()?> грн.</div>
                    <div class="new_price <?echo ($item->get_price()==0)?"":"red"?>"><? echo $item->get_priceForSale()?> грн.</div>
                </div>
            </div>
            <a href="/buy/p/<? echo $DLL->linkInBD($item->get_name(),$item->get_id())?>" class="buy">ЗАКАЗАТЬ</a>
        </a>
    </li>

        <?$i++;}?>

        <!--li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">   <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

              <div class="price_block">
                <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                </div>
              </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
                </a>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
                </a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t2.jpg"/></div></div> </div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">   <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height"> <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>

        <li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">   <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

                <div class="price_block">
                    <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                    </div>
                </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
            </a>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с</div>

                <div class="price_block">
                    <div class="vert_align">

                        <div class="new_price ">9,50 грн.</div>
                    </div>
                </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
            </a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t2.jpg"/></div></div> </div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">   <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height"> <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li-->
    </ul>

    <?}?>

    <script>


        /*
         Get the curent slide
         */

        function currentSlide( current ) {
            $(".current_slide").text(current + " of " + $("#slides").slides("status","total") );
        }

        $(function(){
            /*
             Initialize SlidesJS
             */

            $("#slides").slides({
                navigateEnd: function( current ) {
                    currentSlide( current );
                },
                loaded: function(){
                    currentSlide( 1 );
                }
            });


        });
    </script>

    <script>

        $(document).ready(function()
        {


            speed = 1000
            speed_remove = 5000
            first()
            setTimeout( df,5000);



            $('.product_ul li').hover(
                function() {
                    $(this).find('img').removeAttr('style')

                    var height = $(this).find('img').height();
                    var width  = $(this).find('img').width();
                    height_old = height;
                    width_old = width;
                    height = (height*110)/100;
                    width = (width*110)/100;

                    $(this).find('img').stop().animate({width:width,height:height},300)




                },
                function() {

                    $(this).find('img').stop().animate({width:width_old,height:height_old},300)

                }
            );



        })



        function first()
        {



            $('.block1').animate({left:50},speed-200)
            $('.block2').animate({left:50},speed)
            $('.block3').animate({left:50},speed+200)



        }


        function df(){

            $("#slides").slides("play");
        }




    </script>