<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/slides.js');
$page -> addCss('css/style_slider_main.css');


?>

<script>


    /*
     Get the curent slide
     */

    function currentSlide( current ) {
        $(".current_slide").text(current + " of " + $("#slides").slides("status","total") );
    }

    $(function(){
        /*
         Initialize SlidesJS
         */

        $("#slides").slides({
            navigateEnd: function( current ) {
                currentSlide( current );
            },
            loaded: function(){
                currentSlide( 1 );
            }
        });


    });
</script>

<script>

    $(document).ready(function()
    {

         speed = 1000
        speed_remove = 5000
        first()
        setTimeout( df,5000);



        $('.product_ul li').hover(
            function() {
                $(this).find('img').removeAttr('style')

                var height = $(this).find('img').height();
                var width  = $(this).find('img').width();
                height_old = height;
                width_old = width;
                height = (height*110)/100;
                width = (width*110)/100;

                $(this).find('img').stop().animate({width:width,height:height},300)




            },
            function() {

                $(this).find('img').stop().animate({width:width_old,height:height_old},300)

            }
        );



    })
   var  currentID_2 = setTimeout()
   var  currentID_3 = setTimeout()


function first()
{


    //clearTimeout(currentID_1)
    $('.text1').css({left:-1000,top: 90})
    $('.text2').css({left:-1000,top: 155})
    $('.text3').css({left:-1000,top: 220})
    $('.text1').animate({left:50},speed-200)
    $('.text2').animate({left:50},speed)
    $('.text3').animate({left:50},speed+200)

     currentID_1=setTimeout(function(){

    $('.text1').animate({top:-1000},speed-200)
    $('.text2').animate({left:-1000},speed)
    $('.text3').animate({top:1000},speed+200)
},speed_remove)


}
    function first_remove()
    {
        $('.text1').animate({top:-1000},speed-200)
        $('.text2').animate({left:-1000},speed)
        $('.text3').animate({top:1000},speed+200)

    }
    function second()
    {

      //  clearTimeout(currentID_2)

     $('.text4').css({left:-1000,top: 90,display:'block'})
        $('.text5').css({left:-1000,top: 155,display:'block'})
        $('.text4').animate({left:50},speed-200)
        $('.text5').animate({left:50},speed)
         currentID_2  =  setTimeout(function(){

            $('.text4').animate({left:-1000},speed-400)
            $('.text5').animate({top:1000},speed)
        },speed_remove)
    }
   function second_remove()
    {
        $('.text4').animate({left:-1000},speed-400)
        $('.text5').animate({top:1000},speed)

    }

    function third()
    {
      //  clearTimeout(currentID_3)

        $('.text6').css({left:-1000,top: 90,display:'block'})
        $('.text7').css({left:-1000,top: 155,display:'block'})
        $('.text8').css({left:-1000,top: 220,display:'block'})
        $('.text6').animate({left:50},speed-200)
        $('.text7').animate({left:50},speed)
        $('.text8').animate({left:50},speed+200)
         currentID_3 = setTimeout(function(){

            $('.text6').animate({top:-1000},speed-200)
            $('.text7').animate({left:-1000},speed)
            $('.text8').animate({top:1000},speed+200)
        },speed_remove)
    }
   function third_remove()
    {
        $('.text6').animate({top:-1000},speed-200)
        $('.text7').animate({left:-1000},speed)
        $('.text8').animate({top:1000},speed+200)

    }


function df(){

    $("#slides").slides("play");
}




</script>

<div class="clr"></div>
</div>
<div class="slider">
    <div class="tex_fly block1 text1">Идеальное решение</div>
    <div class="tex_fly block2 text2">для домов</div>
    <div class="tex_fly block3 text3">и котеджей</div>

    <div class="tex_fly block1 text4">Новые перспективы </div>
    <div class="tex_fly block2 text5">в домостроении</div>



    <div class="tex_fly block1 text6">Удобная схема</div>
    <div class="tex_fly block2 text7">прямых поставок</div>
    <div class="tex_fly block3 text8">к Вам на обьект</div>





    <div id="container">

        <!-- start SlidesJS slideshow -->
        <div id="slides">
            <img src="../img/main4.jpg" width="1024" height="360" alt="Slide 1">

            <img src="../img/main6.jpg" width="1024" height="360" alt="Slide 2">

            <img src="../img/main2.jpg" width="1024" height="360" alt="Slide 3">

            <!--img src="../img/main3.jpg" width="1240" height="360" alt="Slide 4">

            <img src="../img/main5.jpg" width="1240" height="360" alt="Slide 5"-->

                  </div>

    </div>
</div>

<div class="w_980">
    <div class="h_50">
        <div class="title_page f_l"><span>Топ</span> предложения строительных материалов</div>
        <div class="price_text f_r">Цены на 10.08.2013</div>
    </div>

    <ul class="product_ul">
        <li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">   <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

              <div class="price_block">
                <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                </div>
              </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
                </a>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
                </a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t2.jpg"/></div></div> </div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">   <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height"> <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>

        <li class="no_mar_left">
            <a href="catalog/Product">
                <div class="max_height">   <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с <br>  доставкой по Донецку  доставкой по Доfgнецку  доставdfgffffffdddddfffdfgкой по Донецку  досfgтавкой по Донецку</div>

                <div class="price_block">
                    <div class="vert_align">
                        <div class="old_price">10,00 грн.</div>
                        <div class="new_price red">9,50 грн.</div>
                    </div>
                </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
            </a>
        </li>


        <li class="">
            <a href="catalog/Product">
                <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
                <div class="text">Кератерм блоки ® 25 с</div>

                <div class="price_block">
                    <div class="vert_align">

                        <div class="new_price ">9,50 грн.</div>
                    </div>
                </div>
                <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
            </a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t2.jpg"/></div></div> </div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку dfsdsg fdhd</div>

            <div class="price_block">
                <div class="vert_align">

                    <div class="new_price ">9,50 грн.</div>
                </div>
            </div>
            <a href="/buy" class="buy">ЗАКАЗАТЬ</a>
        </li>
        <li class="">
            <div class="max_height"> <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal no_mar_left">
            <div class="max_height">   <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t1.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height"> <div class="img"><div><img src="../img/t3.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
        <li class="height_normal">
            <div class="max_height">  <div class="img"><div><img src="../img/t2.jpg"/></div></div></div>
            <div class="text">Кератерм блоки ® 25 с <br> доставкой по Донецку</div>

            <div class="price_block">
                <div class="vert_align">
                    <div class="old_price">10,00 грн.</div>
                    <div class="new_price red">9,50 грн.</div>
                </div>
            </div>
            <div class="buy">ЗАКАЗАТЬ</div>
        </li>
    </ul>


