<?
    $page -> setTitle("Start stroy");
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
$db = db::getInstance();
$dm = new db_manager();




$partners = $dm->getAllPartners();
if (count($partners) > 0)
{


?>
        <h1 >Партнеры</h1>
    <div class="page_partner ">
        <ul>
            <?$i=1;
            foreach($partners as $item) {?>
            <li <? echo ($i%4==1)?'class="no_mar_left"':''?>>
                <div class="img">
                    <div class="vert_al">
                   <a <? echo ($item->get_link())?'href="'.$item->get_link().'"':''?>  ><img src="../img/partners/<? echo $item->get_img()?>"/></a>
                    </div>
                </div>
                <a  <? echo ($item->get_link())?'target="_blank" href="'.$item->get_link().'"':''?>  ><? echo $item->get_name()?></a>
                    <div class="text"><? echo $item->get_des()?></div>

            </li>
        <?$i++;}?>




        </ul>
<?}?>




    </div>

<div class="clr"></div>

<script>
    $( document ).ready(function() {

        $('.page_partner ul li').hover(
            function() {

                $(this).find('img').removeAttr('style')
                var height = $(this).find('img').height();
                var width  = $(this).find('img').width();
                height_old = height;
                width_old = width;
                height = (height*110)/100;
                width = (width*110)/100;

                $(this).find('img').stop().animate({width:width,height:height},300)
                $(this).find('a').css({textDecoration:'underline'})


            },
            function() {
                $(this).find('a').css({textDecoration:'none'})
                $(this).find('img').stop().animate({width:width_old,height:height_old},300)

            }
        );


    })

</script>