<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/jquery.form.js','js/review.js');
$id = $controller->getParam(1);
require_once 'class.review.php';

require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
require_once 'class.review.php';
$db = db::getInstance();
$dm = new db_manager();
$rew = new review($id);
$db->query("SELECT id FROM reviews WHERE `show`=1 AND deleted=0 ORDER BY dateCreate DESC");
$allReviews = $db->getArray();
?>

<script>
    function getName (str){
        if (str.lastIndexOf('\\')){
            var i = str.lastIndexOf('\\')+1;
        }
        else{
            var i = str.lastIndexOf('/')+1;
        }
        var filename = str.slice(i);
        var uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
<div class="catalog_page reviews_page revies_page_more" >
<h1 class="f_l">Отзыв</h1> <a  class="bt_back bt_more  f_r" href=/reviews>НАЗАД</a>

    <table>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/client/<? echo $dm->getImgClient($rew->get_client_id())?>"/></div>

                </div>
            <div class="text">
                <p class="name"><? echo $dm->getClientName($rew->get_client_id())?></p>
                <p class="date"><? echo $DLL->getRusDate($rew->get_dateCreate())?></p>
                               <p class="text_rev"><? echo $rew->get_text()?></p>



            </div>

            </td>

        </tr>

    </table>
<?if(count($allReviews)>1){
    for($i=0;$i<count($allReviews);$i++){
        if($allReviews[$i]['id']==$id){
            $cur = $i;
        }
    }?>
    <div class="navigate_arrow">
        <?if($cur!=0){?>
        <a href="/reviews/more/<?=$allReviews[$cur-1]['id']?>" class=" f_l">Предыдущий отзыв</a>
        <?}?>
        <?if($cur!=(count($allReviews)-1)){?>
        <a href="/reviews/more/<?=$allReviews[$cur+1]['id']?>" class=" f_r">Следующий отзыв</a>
        <?}?>
    </div>
    <?}?>
    <div class="clr"></div>


    <h2>Оставить отзыв</h2>



    <div class="form_reviews">
        <form  name="review_full"  method="POST" >
            <div class="f_l">
                <textarea id="review" name="review"></textarea>
                <p>Ваш отзыв:</p>
                <div  class="clr"></div>
                <div class="fileform">
                    <div id="fileformlabel"></div>
                    <div class="selectbutton">Обзор</div>
                    <input type="file" name="upload" id="upload" onchange="getName(this.value);" />
                </div>
                <p style="padding-right: 12px;margin-top: 5px;">Ваше фото:</p>
            </div>

            <div class="f_r">

                <input id="name" name="name" type="text">
                <p>* Ваше имя:</p>
                <div class="clr"></div>
                <input id="phone" name="phone"  type="text">
                <p>   * Телефон:</p>

                <div class="clr"></div>
                <input   type="button" id="add_rw" class="bt_send f_r" value="ОТПРАВИТЬ"/>
            </div>


            <div class="clr"></div>
        </form>
    </div>

<div class="clr"></div>

</div>