<?
    $page -> setTitle("Start stroy");
$page -> addScript('js/jquery.form.js');
require_once $root."/lib/class.invis.db.php";
require_once $root."/lib/class.db.manager.php";
require_once $root."/lib/class.dll.php";
require_once 'class.review.php';
$db = db::getInstance();
$dm = new db_manager();
$reviews = $dm->getAllReviewsShow();

if (count($reviews) > 0)
{


?>
<script>
    function getName (str){
        if (str.lastIndexOf('\\')){
            var i = str.lastIndexOf('\\')+1;
        }
        else{
            var i = str.lastIndexOf('/')+1;
        }
        var filename = str.slice(i);
        var uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
<div class="catalog_page reviews_page">
<h1 >Все отзывы</h1>

    <table>


        <?$i=1;
        foreach($reviews as $item) {?>
            <?echo ($i%2==1)?'<tr>':''?>

             <td <? echo ($i%2==1)?'class="left"':'class="right"'?>>

                 <div class="img">
                     <div class="img_top"></div>
                     <div class="all"> <img src="../img/client/m_<? echo $dm->getImgClient($item->get_client_id())?>"/></div>

                 </div>
                 <div class="text">

                     <p class="text_rev"><? echo $item->get_text()?></p>
                     <p class="name"><? echo $dm->getClientName($item->get_client_id())?></p>
                     <p class="date"><? echo date('d.m.Y',strtotime($item->get_dateCreate()))?></p>
                 </div>
                 <?
                 echo (strlen( $item->get_text())>450)?'<div class="clr"></div>
                 <a  href="/reviews/more/'.$item->get_id().'"class="bt_more">ПОДРОБНЕЕ</a>':''?>

             </td>
            <? echo ($i%2==0)?'</tr>':''?>

            <?$i++;}?>







        <!--tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
            <div class="text">
                <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                <p class="name">Сергей</p>
                <p class="date">10 июля 2013 г.</p>
            </div>

            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей Сергей Сергей Сергей Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
                <div class="clr"></div>

            </td>
        </tr>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. прошлом году газобетон и битумную черепицу прошлом году газобетон и битумную черепицу прошлом году газобетон и битумную черепицу Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>

            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>

            </td>
        </tr>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
            <div class="clr"></div>


            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
                <div class="clr"></div>
                <a  href="/reviews/more"class="bt_more">ПОДРОБНЕЕ</a>
            </td>
        </tr-->

    </table>
    <?}?>
    <div class="clr"></div>


    <div class="navigate ">



        <a href=""><span class="active">1</span></a>
        <a href=""><span>2</span></a>
        <a href=""><span>3</span></a>
        <a href=""><span>4</span></a>
        <a href=""><span>5</span></a>

    </div>
    <div class="clr"></div>
    <h2>Оставить отзыв</h2>



    <div class="form_reviews">
        <form  name="review_full"  method="POST" >
                <div class="f_l">
                    <textarea id="review" name="review"></textarea>
                    <p>Ваш отзыв:</p>
                    <div  class="clr"></div>
                    <div class="fileform">
                        <div id="fileformlabel"></div>
                        <div class="selectbutton">Обзор</div>
                        <input type="file" name="upload" id="upload" onchange="getName(this.value);" />
                    </div>
                    <p style="padding-right: 12px;margin-top: 5px;">Ваше фото:</p>
                </div>

                <div class="f_r">

                    <input id="name" name="name" type="text">
                    <p>* Ваше имя:</p>
                    <div class="clr"></div>
                    <input id="phone" name="phone"  type="text">
                    <p>   * Телефон:</p>

                                <div class="clr"></div>
                    <input   type="button" id="add_rw" class="bt_send f_r" value="ОТПРАВИТЬ"/>
                </div>


        <div class="clr"></div>
        </form>
    </div>

<div class="clr"></div>

</div>