<?
    $page -> setTitle("Start stroy");

?>

<script>
    function getName (str){
        if (str.lastIndexOf('\\')){
            var i = str.lastIndexOf('\\')+1;
        }
        else{
            var i = str.lastIndexOf('/')+1;
        }
        var filename = str.slice(i);
        var uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
<div class="catalog_page reviews_page revies_page_more" >
<h1 class="f_l">Отзыв</h1> <a  class="bt_back bt_more  f_r" href=/reviews>НАЗАД</a>

    <table>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
            <div class="text">
                <p class="name">Сергей Cthuttdbx</p>
                <p class="date">10 июля 2013 г.</p>
                               <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу.Купил в прошлом году газобетон и битумную черепицу.Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>

                <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно Купил в прошлом году газобетон и битумную черепицу. работали. </p>

            </div>

            </td>

        </tr>

    </table>

    <div class="navigate_arrow">
        <a href="/" class=" f_l">Предыдущий отзыв</a>
        <a href="/" class=" f_r">Следующий отзыв</a>

    </div>
    <div class="clr"></div>


    <h2>Оставить отзыв</h2>



    <div class="form_reviews">

        <div class="f_l">
            <textarea></textarea>
            <p>Ваш отзыв:</p>

            <div  class="clr"></div>


            <div class="fileform">
                <div id="fileformlabel"></div>
                <div class="selectbutton">Обзор</div>
                <input type="file" name="upload" id="upload" onchange="getName(this.value);" />
            </div>
            <p style="padding-right: 12px;margin-top: 5px;">Ваше фото:</p>
        </div>

        <div class="f_r">

            <input type="text">
            <p>* Ваше имя:</p>



            <div class="clr"></div>
            <input type="text">
            <p>   * Телефон:</p>



            <div class="clr"></div>
            <div class="bt_send f_r">ОТПРАВИТЬ</div>
        </div>
        <div class="clr"></div>
    </div>

<div class="clr"></div>

</div>