<?
    $page -> setTitle("Start stroy");

?>
<script>
    function getName (str){
        if (str.lastIndexOf('\\')){
            var i = str.lastIndexOf('\\')+1;
        }
        else{
            var i = str.lastIndexOf('/')+1;
        }
        var filename = str.slice(i);
        var uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
<div class="catalog_page reviews_page">
<h1 >Все отзывы</h1>

    <table>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
            <div class="text">
                <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                <p class="name">Сергей</p>
                <p class="date">10 июля 2013 г.</p>
            </div>

            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей Сергей Сергей Сергей Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
                <div class="clr"></div>

            </td>
        </tr>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. прошлом году газобетон и битумную черепицу прошлом году газобетон и битумную черепицу прошлом году газобетон и битумную черепицу Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>

            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>

            </td>
        </tr>
        <tr>
            <td class="left">
                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
            <div class="clr"></div>


            </td>
            <td class="right">

                <div class="img">
                    <div class="img_top"></div>
                    <div class="all"> <img src="../img/rew1.jpg"/></div>

                </div>
                <div class="text">
                    <p class="text_rev">Купил в прошлом году газобетон и битумную черепицу. Высшая оценка, все бы так ответственно работали. </p>
                    <p class="name">Сергей</p>
                    <p class="date">10 июля 2013 г.</p>
                </div>
                <div class="clr"></div>
                <a  href="/reviews/more"class="bt_more">ПОДРОБНЕЕ</a>
            </td>
        </tr>
    </table>
    <div class="clr"></div>


    <div class="navigate ">



        <a href=""><span class="active">1</span></a>
        <a href=""><span>2</span></a>
        <a href=""><span>3</span></a>
        <a href=""><span>4</span></a>
        <a href=""><span>5</span></a>

    </div>
    <div class="clr"></div>
    <h2>Оставить отзыв</h2>



    <div class="form_reviews">

        <div class="f_l">
            <textarea ></textarea>
            <p>Ваш отзыв:</p>

            <div  class="clr"></div>


            <div class="fileform">
                <div id="fileformlabel"></div>
                <div class="selectbutton">Обзор</div>
                <input type="file" name="upload" id="upload" onchange="getName(this.value);" />
            </div>
            <p style="padding-right: 12px;margin-top: 5px;">Ваше фото:</p>
        </div>

        <div class="f_r">

            <input type="text">
            <p>* Ваше имя:</p>



            <div class="clr"></div>
            <input type="text">
            <p>   * Телефон:</p>



            <div class="clr"></div>
            <div class="bt_send f_r">ОТПРАВИТЬ</div>
        </div>
        <div class="clr"></div>
    </div>

<div class="clr"></div>

</div>